-- Add up migration script here
CREATE TABLE
    IF NOT EXISTS webview_layout (
        name TEXT PRIMARY KEY,
        x REAL NOT NULL DEFAULT 0,
        y REAL NOT NULL DEFAULT 0,
        width REAL NOT NULL DEFAULT 200,
        height REAL NOT NULL DEFAULT 200
    );

INSERT INTO
    webview_layout (name, x, y, width, height)
VALUES
    ('inputs', 50.0, 50.0, 400.0, 150.0),
    ('standings', 200.0, 200.0, 400.0, 600.0),
    ('track-map', 600.0, 200.0, 300.0, 300.0),
    ('relative', 100.0, 500.0, 400.0, 200.0) ON CONFLICT (name) DO NOTHING;

----- Settings
CREATE TABLE
    IF NOT EXISTS app_settings (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        use_metric_system INTEGER NOT NULL DEFAULT 0 CHECK (use_metric_system IN (0, 1)),
        startup_overlay_minimized INTEGER NOT NULL DEFAULT 0 CHECK (startup_overlay_minimized IN (0, 1)),
        minimize_to_system_tray INTEGER NOT NULL DEFAULT 0 CHECK (minimize_to_system_tray IN (0, 1)),
        show_race_control_at_startup INTEGER NOT NULL DEFAULT 0 CHECK (show_race_control_at_startup IN (0, 1)),
        use_ctrl_f6_instead_of_f6 INTEGER NOT NULL DEFAULT 0 CHECK (use_ctrl_f6_instead_of_f6 IN (0, 1)),
        use_hardware_acceleration INTEGER NOT NULL DEFAULT 0 CHECK (use_hardware_acceleration IN (0, 1)),
        lower_fps INTEGER NOT NULL DEFAULT 0 CHECK (lower_fps IN (0, 1)),
        show_overlays_in_taskbar INTEGER NOT NULL DEFAULT 0 CHECK (show_overlays_in_taskbar IN (0, 1)),
        vr_compatibility INTEGER NOT NULL DEFAULT 0 CHECK (vr_compatibility IN (0, 1))
    );

INSERT INTO
    app_settings (id)
VALUES
    (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE
    IF NOT EXISTS page_settings (
        page TEXT NOT NULL,
        setting TEXT NOT NULL,
        value INTEGER NOT NULL DEFAULT 0 CHECK (value IN (0, 1)),
        PRIMARY KEY (page, setting)
    );

INSERT INTO
    page_settings (page, setting, value)
VALUES
    -- ** INPUTS
    ('inputs', 'is_active', 0),
    -- General Tab
    ('inputs', 'general.in_car', 0),
    ('inputs', 'general.out_of_car', 0),
    ('inputs', 'general.spotting', 0),
    ('inputs', 'general.in_garage', 0),
    -- Content Tab
    ('inputs', 'content.rev_lights', 0),
    ('inputs', 'content.gear_and_speed', 0),
    ('inputs', 'content.input_bars', 0),
    ('inputs', 'content.steering_wheel', 0),
    ('inputs', 'content.boost_ers', 0),
    ('inputs', 'content.corner_speed', 0),
    -- Header Tab
    ('inputs', 'header.session_name', 0),
    ('inputs', 'header.event_type', 0),
    ('inputs', 'header.local_time_24h', 0),
    ('inputs', 'header.local_time_am_pm', 0),
    ('inputs', 'header.in_sim_time_24h', 0),
    ('inputs', 'header.in_sim_time_am_pm', 0),
    ('inputs', 'header.air_temp', 0),
    ('inputs', 'header.track_temp', 0),
    ('inputs', 'header.humidity', 0),
    ('inputs', 'header.fog_level', 0),
    ('inputs', 'header.time_remaining', 0),
    ('inputs', 'header.laps_remaining', 0),
    ('inputs', 'header.incident_count', 0),
    ('inputs', 'header.current_lap_time', 0),
    ('inputs', 'header.session_best_lap_time', 0),
    ('inputs', 'header.last_lap_time', 0),
    ('inputs', 'header.last_lap_time_calculated', 0),
    ('inputs', 'header.lap_delta_best', 0),
    ('inputs', 'header.lap_delta_optimal', 0),
    ('inputs', 'header.lap_delta_session_best', 0),
    ('inputs', 'header.lap_delta_session_optimal', 0),
    ('inputs', 'header.lap_delta_session_last', 0),
    ('inputs', 'header.brake_bias', 0),
    ('inputs', 'header.fuel_level', 0),
    ('inputs', 'header.water_temp', 0),
    ('inputs', 'header.oil_temp', 0),
    ('inputs', 'header.sof', 0),
    ('inputs', 'header.current_stint_in_laps', 0),
    ('inputs', 'header.current_stint_in_time', 0),
    ('inputs', 'header.rpm', 0),
    ('inputs', 'header.deploy_mode', 0),
    ('inputs', 'header.arb_front', 0),
    ('inputs', 'header.arb_rear', 0),
    ('inputs', 'header.abs', 0),
    ('inputs', 'header.tc_1', 0),
    ('inputs', 'header.tc_2', 0),
    ('inputs', 'header.weight_jacker', 0),
    ('inputs', 'header.rear_brake_valve', 0),
    ('inputs', 'header.precippitation', 0),
    ('inputs', 'header.track_wetness', 0),
    ('inputs', 'header.weather_declared_wet', 0),
    ('inputs', 'header.pit_time_loss', 0),
    ('inputs', 'header.wind_direction_for_driver', 0),
    (
        'inputs',
        'header.predicted_position_after_pit_stop',
        0
    ),
    ('inputs', 'header.irating_and_gain', 0),
    ('inputs', 'header.push_to_pass', 0),
    -- Footer Tab
    ('inputs', 'footer.session_name', 0),
    ('inputs', 'footer.event_type', 0),
    ('inputs', 'footer.local_time_24h', 0),
    ('inputs', 'footer.local_time_am_pm', 0),
    ('inputs', 'footer.in_sim_time_24h', 0),
    ('inputs', 'footer.in_sim_time_am_pm', 0),
    ('inputs', 'footer.air_temp', 0),
    ('inputs', 'footer.track_temp', 0),
    ('inputs', 'footer.humidity', 0),
    ('inputs', 'footer.fog_level', 0),
    ('inputs', 'footer.time_remaining', 0),
    ('inputs', 'footer.laps_remaining', 0),
    ('inputs', 'footer.incident_count', 0),
    ('inputs', 'footer.current_lap_time', 0),
    ('inputs', 'footer.session_best_lap_time', 0),
    ('inputs', 'footer.last_lap_time', 0),
    ('inputs', 'footer.last_lap_time_calculated', 0),
    ('inputs', 'footer.lap_delta_best', 0),
    ('inputs', 'footer.lap_delta_optimal', 0),
    ('inputs', 'footer.lap_delta_session_best', 0),
    ('inputs', 'footer.lap_delta_session_optimal', 0),
    ('inputs', 'footer.lap_delta_session_last', 0),
    ('inputs', 'footer.brake_bias', 0),
    ('inputs', 'footer.fuel_level', 0),
    ('inputs', 'footer.water_temp', 0),
    ('inputs', 'footer.oil_temp', 0),
    ('inputs', 'footer.sof', 0),
    ('inputs', 'footer.current_stint_in_laps', 0),
    ('inputs', 'footer.current_stint_in_time', 0),
    ('inputs', 'footer.rpm', 0),
    ('inputs', 'footer.deploy_mode', 0),
    ('inputs', 'footer.arb_front', 0),
    ('inputs', 'footer.arb_rear', 0),
    ('inputs', 'footer.abs', 0),
    ('inputs', 'footer.tc_1', 0),
    ('inputs', 'footer.tc_2', 0),
    ('inputs', 'footer.weight_jacker', 0),
    ('inputs', 'footer.rear_brake_valve', 0),
    ('inputs', 'footer.precippitation', 0),
    ('inputs', 'footer.track_wetness', 0),
    ('inputs', 'footer.weather_declared_wet', 0),
    ('inputs', 'footer.pit_time_loss', 0),
    ('inputs', 'footer.wind_direction_for_driver', 0),
    (
        'inputs',
        'footer.predicted_position_after_pit_stop',
        0
    ),
    ('inputs', 'footer.irating_and_gain', 0),
    ('inputs', 'footer.push_to_pass', 0),
    -- ** STANDINGS
    ('standings', 'is_active', 0),
    -- General Tab
    ('standings', 'general.in_car', 0),
    ('standings', 'general.out_of_car', 0),
    ('standings', 'general.spotting', 0),
    ('standings', 'general.in_garage', 0),
    -- Content Tab
    ('standings', 'content.position', 0),
    ('standings', 'content.class_badge_color', 0),
    ('standings', 'content.car_number', 0),
    ('standings', 'content.team_name', 0),
    ('standings', 'content.license', 0),
    ('standings', 'content.irating', 0),
    ('standings', 'content.car_brand', 0),
    ('standings', 'content.interval', 0),
    ('standings', 'content.fastest_lap_time', 0),
    ('standings', 'content.gap', 0),
    ('standings', 'content.lap_delta', 0),
    ('standings', 'content.positions_gained', 0),
    ('standings', 'content.black_flag', 0),
    ('standings', 'content.driver_name', 0),
    ('standings', 'content.pitstop_status', 0),
    ('standings', 'content.time_in_pitlane', 0),
    ('standings', 'content.relative_time', 0),
    ('standings', 'content.time_in_pitbox', 0),
    ('standings', 'content.current_stint_length', 0),
    ('standings', 'content.joker_lap', 0),
    ('standings', 'content.tire_compound', 0),
    ('standings', 'content.driver_tags', 0),
    ('standings', 'content.avg_5_laps', 0),
    ('standings', 'content.avg_10_laps', 0),
    ('standings', 'content.push_to_pass', 0),
    ('standings', 'content.country_flag', 0),
    -- Class Header Tab
    ('standings', 'class_header.class_name', 0),
    ('standings', 'class_header.drivers_in_class', 0),
    ('standings', 'class_header.class_sof', 0),
    -- Header Tab
    ('standings', 'header.session_name', 0),
    ('standings', 'header.event_type', 0),
    ('standings', 'header.local_time_24h', 0),
    ('standings', 'header.local_time_am_pm', 0),
    ('standings', 'header.in_sim_time_24h', 0),
    ('standings', 'header.in_sim_time_am_pm', 0),
    ('standings', 'header.air_temp', 0),
    ('standings', 'header.track_temp', 0),
    ('standings', 'header.humidity', 0),
    ('standings', 'header.fog_level', 0),
    ('standings', 'header.time_remaining', 0),
    ('standings', 'header.laps_remaining', 0),
    ('standings', 'header.incident_count', 0),
    ('standings', 'header.current_lap_time', 0),
    ('standings', 'header.session_best_lap_time', 0),
    ('standings', 'header.last_lap_time', 0),
    ('standings', 'header.last_lap_time_calculated', 0),
    ('standings', 'header.lap_delta_best', 0),
    ('standings', 'header.lap_delta_optimal', 0),
    ('standings', 'header.lap_delta_session_best', 0),
    (
        'standings',
        'header.lap_delta_session_optimal',
        0
    ),
    ('standings', 'header.lap_delta_session_last', 0),
    ('standings', 'header.brake_bias', 0),
    ('standings', 'header.fuel_level', 0),
    ('standings', 'header.water_temp', 0),
    ('standings', 'header.oil_temp', 0),
    ('standings', 'header.sof', 0),
    ('standings', 'header.current_stint_in_laps', 0),
    ('standings', 'header.current_stint_in_time', 0),
    ('standings', 'header.rpm', 0),
    ('standings', 'header.deploy_mode', 0),
    ('standings', 'header.arb_front', 0),
    ('standings', 'header.arb_rear', 0),
    ('standings', 'header.abs', 0),
    ('standings', 'header.tc_1', 0),
    ('standings', 'header.tc_2', 0),
    ('standings', 'header.weight_jacker', 0),
    ('standings', 'header.rear_brake_valve', 0),
    ('standings', 'header.precippitation', 0),
    ('standings', 'header.track_wetness', 0),
    ('standings', 'header.weather_declared_wet', 0),
    ('standings', 'header.pit_time_loss', 0),
    (
        'standings',
        'header.wind_direction_for_driver',
        0
    ),
    (
        'standings',
        'header.predicted_position_after_pit_stop',
        0
    ),
    ('standings', 'header.irating_and_gain', 0),
    ('standings', 'header.push_to_pass', 0),
    -- ** RELATIVE
    ('relative', 'is_active', 0),
    -- General Tab
    ('relative', 'general.in_car', 0),
    ('relative', 'general.out_of_car', 0),
    ('relative', 'general.spotting', 0),
    ('relative', 'general.in_garage', 0),
    -- Content Tab
    ('relative', 'content.position', 0),
    ('relative', 'content.class_badge_color', 0),
    ('relative', 'content.driver_name', 0),
    ('relative', 'content.license', 0),
    ('relative', 'content.irating', 0),
    ('relative', 'content.relative_time', 0),
    ('relative', 'content.team_name', 0),
    ('relative', 'content.car_brand', 0),
    ('relative', 'content.intervals', 0),
    ('relative', 'content.gap', 0),
    ('relative', 'content.fastest_lap_time', 0),
    ('relative', 'content.last_lap_time', 0),
    ('relative', 'content.lap_delta', 0),
    ('relative', 'content.pitstop_status', 0),
    ('relative', 'content.time_in_pitlane', 0),
    ('relative', 'content.time_in_pitbox', 0),
    ('relative', 'content.current_stint_length', 0),
    ('relative', 'content.positions_gained', 0),
    ('relative', 'content.joker_lap', 0),
    ('relative', 'content.tire_compound', 0),
    ('relative', 'content.driver_tags', 0),
    ('relative', 'content.black_flag', 0),
    ('relative', 'content.avg_5_laps', 0),
    ('relative', 'content.avg_10_laps', 0),
    ('relative', 'content.push_to_pass', 0),
    ('relative', 'content.country_flag', 0),
    -- Header Tab
    ('relative', 'header.session_name', 0),
    ('relative', 'header.event_type', 0),
    ('relative', 'header.local_time_24h', 0),
    ('relative', 'header.local_time_am_pm', 0),
    ('relative', 'header.in_sim_time_24h', 0),
    ('relative', 'header.in_sim_time_am_pm', 0),
    ('relative', 'header.air_temp', 0),
    ('relative', 'header.track_temp', 0),
    ('relative', 'header.humidity', 0),
    ('relative', 'header.fog_level', 0),
    ('relative', 'header.time_remaining', 0),
    ('relative', 'header.laps_remaining', 0),
    ('relative', 'header.incident_count', 0),
    ('relative', 'header.current_lap_time', 0),
    ('relative', 'header.session_best_lap_time', 0),
    ('relative', 'header.last_lap_time', 0),
    ('relative', 'header.last_lap_time_calculated', 0),
    ('relative', 'header.lap_delta_best', 0),
    ('relative', 'header.lap_delta_optimal', 0),
    ('relative', 'header.lap_delta_session_best', 0),
    ('relative', 'header.lap_delta_session_optimal', 0),
    ('relative', 'header.lap_delta_session_last', 0),
    ('relative', 'header.brake_bias', 0),
    ('relative', 'header.fuel_level', 0),
    ('relative', 'header.water_temp', 0),
    ('relative', 'header.oil_temp', 0),
    ('relative', 'header.sof', 0),
    ('relative', 'header.current_stint_in_laps', 0),
    ('relative', 'header.current_stint_in_time', 0),
    ('relative', 'header.rpm', 0),
    ('relative', 'header.deploy_mode', 0),
    ('relative', 'header.arb_front', 0),
    ('relative', 'header.arb_rear', 0),
    ('relative', 'header.abs', 0),
    ('relative', 'header.tc_1', 0),
    ('relative', 'header.tc_2', 0),
    ('relative', 'header.weight_jacker', 0),
    ('relative', 'header.rear_brake_valve', 0),
    ('relative', 'header.precippitation', 0),
    ('relative', 'header.track_wetness', 0),
    ('relative', 'header.weather_declared_wet', 0),
    ('relative', 'header.pit_time_loss', 0),
    ('relative', 'header.wind_direction_for_driver', 0),
    (
        'relative',
        'header.predicted_position_after_pit_stop',
        0
    ),
    ('relative', 'header.irating_and_gain', 0),
    ('relative', 'header.push_to_pass', 0),
    -- ** Footer Tab
    ('relative', 'footer.session_name', 0),
    ('relative', 'footer.event_type', 0),
    ('relative', 'footer.local_time_24h', 0),
    ('relative', 'footer.local_time_am_pm', 0),
    ('relative', 'footer.in_sim_time_24h', 0),
    ('relative', 'footer.in_sim_time_am_pm', 0),
    ('relative', 'footer.air_temp', 0),
    ('relative', 'footer.track_temp', 0),
    ('relative', 'footer.humidity', 0),
    ('relative', 'footer.fog_level', 0),
    ('relative', 'footer.time_remaining', 0),
    ('relative', 'footer.laps_remaining', 0),
    ('relative', 'footer.incident_count', 0),
    ('relative', 'footer.current_lap_time', 0),
    ('relative', 'footer.session_best_lap_time', 0),
    ('relative', 'footer.last_lap_time', 0),
    ('relative', 'footer.last_lap_time_calculated', 0),
    ('relative', 'footer.lap_delta_best', 0),
    ('relative', 'footer.lap_delta_optimal', 0),
    ('relative', 'footer.lap_delta_session_best', 0),
    ('relative', 'footer.lap_delta_session_optimal', 0),
    ('relative', 'footer.lap_delta_session_last', 0),
    ('relative', 'footer.brake_bias', 0),
    ('relative', 'footer.fuel_level', 0),
    ('relative', 'footer.water_temp', 0),
    ('relative', 'footer.oil_temp', 0),
    ('relative', 'footer.sof', 0),
    ('relative', 'footer.current_stint_in_laps', 0),
    ('relative', 'footer.current_stint_in_time', 0),
    ('relative', 'footer.rpm', 0),
    ('relative', 'footer.deploy_mode', 0),
    ('relative', 'footer.arb_front', 0),
    ('relative', 'footer.arb_rear', 0),
    ('relative', 'footer.abs', 0),
    ('relative', 'footer.tc_1', 0),
    ('relative', 'footer.tc_2', 0),
    ('relative', 'footer.weight_jacker', 0),
    ('relative', 'footer.rear_brake_valve', 0),
    ('relative', 'footer.precippitation', 0),
    ('relative', 'footer.track_wetness', 0),
    ('relative', 'footer.weather_declared_wet', 0),
    ('relative', 'footer.pit_time_loss', 0),
    ('relative', 'footer.wind_direction_for_driver', 0),
    (
        'relative',
        'footer.predicted_position_after_pit_stop',
        0
    ),
    ('relative', 'footer.irating_and_gain', 0),
    ('relative', 'footer.push_to_pass', 0),
    -- FUEL CALCULATOR
    ('fuel_calculator', 'is_active', 0),
    -- General Tab
    ('fuel_calculator', 'general.in_car', 0),
    ('fuel_calculator', 'general.out_of_car', 0),
    ('fuel_calculator', 'general.spotting', 0),
    ('fuel_calculator', 'general.in_garage', 0),
    -- Content Tab
    (
        'fuel_calculator',
        'content.average_last_5_laps',
        0
    ),
    ('fuel_calculator', 'content.last_lap', 0),
    ('fuel_calculator', 'content.qualy_lap', 0),
    ('fuel_calculator', 'content.average_10_laps', 0),
    (
        'fuel_calculator',
        'content.minimal_usage_in_session',
        0
    ),
    (
        'fuel_calculator',
        'content.maximum_usage_in_session',
        0
    ),
    -- Header Tab
    ('fuel_calculator', 'header.session_name', 0),
    ('fuel_calculator', 'header.event_type', 0),
    ('fuel_calculator', 'header.local_time_24h', 0),
    ('fuel_calculator', 'header.local_time_am_pm', 0),
    ('fuel_calculator', 'header.in_sim_time_24h', 0),
    ('fuel_calculator', 'header.in_sim_time_am_pm', 0),
    ('fuel_calculator', 'header.air_temp', 0),
    ('fuel_calculator', 'header.track_temp', 0),
    ('fuel_calculator', 'header.humidity', 0),
    ('fuel_calculator', 'header.fog_level', 0),
    ('fuel_calculator', 'header.time_remaining', 0),
    ('fuel_calculator', 'header.laps_remaining', 0),
    ('fuel_calculator', 'header.incident_count', 0),
    ('fuel_calculator', 'header.current_lap_time', 0),
    (
        'fuel_calculator',
        'header.session_best_lap_time',
        0
    ),
    ('fuel_calculator', 'header.last_lap_time', 0),
    (
        'fuel_calculator',
        'header.last_lap_time_calculated',
        0
    ),
    ('fuel_calculator', 'header.lap_delta_best', 0),
    ('fuel_calculator', 'header.lap_delta_optimal', 0),
    (
        'fuel_calculator',
        'header.lap_delta_session_best',
        0
    ),
    (
        'fuel_calculator',
        'header.lap_delta_session_optimal',
        0
    ),
    (
        'fuel_calculator',
        'header.lap_delta_session_last',
        0
    ),
    ('fuel_calculator', 'header.brake_bias', 0),
    ('fuel_calculator', 'header.fuel_level', 0),
    ('fuel_calculator', 'header.water_temp', 0),
    ('fuel_calculator', 'header.oil_temp', 0),
    ('fuel_calculator', 'header.sof', 0),
    (
        'fuel_calculator',
        'header.current_stint_in_laps',
        0
    ),
    (
        'fuel_calculator',
        'header.current_stint_in_time',
        0
    ),
    ('fuel_calculator', 'header.rpm', 0),
    ('fuel_calculator', 'header.deploy_mode', 0),
    ('fuel_calculator', 'header.arb_front', 0),
    ('fuel_calculator', 'header.arb_rear', 0),
    ('fuel_calculator', 'header.abs', 0),
    ('fuel_calculator', 'header.tc_1', 0),
    ('fuel_calculator', 'header.tc_2', 0),
    ('fuel_calculator', 'header.weight_jacker', 0),
    ('fuel_calculator', 'header.rear_brake_valve', 0),
    ('fuel_calculator', 'header.precippitation', 0),
    ('fuel_calculator', 'header.track_wetness', 0),
    (
        'fuel_calculator',
        'header.weather_declared_wet',
        0
    ),
    ('fuel_calculator', 'header.pit_time_loss', 0),
    (
        'fuel_calculator',
        'header.wind_direction_for_driver',
        0
    ),
    (
        'fuel_calculator',
        'header.predicted_position_after_pit_stop',
        0
    ),
    ('fuel_calculator', 'header.irating_and_gain', 0),
    ('fuel_calculator', 'header.push_to_pass', 0),
    -- Footer Tab
    ('fuel_calculator', 'footer.session_name', 0),
    ('fuel_calculator', 'footer.event_type', 0),
    ('fuel_calculator', 'footer.local_time_24h', 0),
    ('fuel_calculator', 'footer.local_time_am_pm', 0),
    ('fuel_calculator', 'footer.in_sim_time_24h', 0),
    ('fuel_calculator', 'footer.in_sim_time_am_pm', 0),
    ('fuel_calculator', 'footer.air_temp', 0),
    ('fuel_calculator', 'footer.track_temp', 0),
    ('fuel_calculator', 'footer.humidity', 0),
    ('fuel_calculator', 'footer.fog_level', 0),
    ('fuel_calculator', 'footer.time_remaining', 0),
    ('fuel_calculator', 'footer.laps_remaining', 0),
    ('fuel_calculator', 'footer.incident_count', 0),
    ('fuel_calculator', 'footer.current_lap_time', 0),
    (
        'fuel_calculator',
        'footer.session_best_lap_time',
        0
    ),
    ('fuel_calculator', 'footer.last_lap_time', 0),
    (
        'fuel_calculator',
        'footer.last_lap_time_calculated',
        0
    ),
    ('fuel_calculator', 'footer.lap_delta_best', 0),
    ('fuel_calculator', 'footer.lap_delta_optimal', 0),
    (
        'fuel_calculator',
        'footer.lap_delta_session_best',
        0
    ),
    (
        'fuel_calculator',
        'footer.lap_delta_session_optimal',
        0
    ),
    (
        'fuel_calculator',
        'footer.lap_delta_session_last',
        0
    ),
    ('fuel_calculator', 'footer.brake_bias', 0),
    ('fuel_calculator', 'footer.fuel_level', 0),
    ('fuel_calculator', 'footer.water_temp', 0),
    ('fuel_calculator', 'footer.oil_temp', 0),
    ('fuel_calculator', 'footer.sof', 0),
    (
        'fuel_calculator',
        'footer.current_stint_in_laps',
        0
    ),
    (
        'fuel_calculator',
        'footer.current_stint_in_time',
        0
    ),
    ('fuel_calculator', 'footer.rpm', 0),
    ('fuel_calculator', 'footer.deploy_mode', 0),
    ('fuel_calculator', 'footer.arb_front', 0),
    ('fuel_calculator', 'footer.arb_rear', 0),
    ('fuel_calculator', 'footer.abs', 0),
    ('fuel_calculator', 'footer.tc_1', 0),
    ('fuel_calculator', 'footer.tc_2', 0),
    ('fuel_calculator', 'footer.weight_jacker', 0),
    ('fuel_calculator', 'footer.rear_brake_valve', 0),
    ('fuel_calculator', 'footer.precippitation', 0),
    ('fuel_calculator', 'footer.track_wetness', 0),
    (
        'fuel_calculator',
        'footer.weather_declared_wet',
        0
    ),
    ('fuel_calculator', 'footer.pit_time_loss', 0),
    (
        'fuel_calculator',
        'footer.wind_direction_for_driver',
        0
    ),
    (
        'fuel_calculator',
        'footer.predicted_position_after_pit_stop',
        0
    ),
    ('fuel_calculator', 'footer.irating_and_gain', 0),
    ('fuel_calculator', 'footer.push_to_pass', 0),
    -- SPOTTER
    ('spotter', 'is_active', 0),
    -- General Tab
    ('spotter', 'general.in_car', 0),
    ('spotter', 'general.out_of_car', 0),
    ('spotter', 'general.spotting', 0),
    ('spotter', 'general.in_garage', 0) ON CONFLICT (page, setting) DO NOTHING;

CREATE TABLE
    IF NOT EXISTS page_setting_display (
        page TEXT NOT NULL,
        setting TEXT NOT NULL,
        session TEXT NOT NULL CHECK (session IN ('practice', 'qualy', 'race')),
        is_visible INTEGER NOT NULL DEFAULT 1 CHECK (is_visible IN (0, 1)),
        PRIMARY KEY (page, setting, session),
        FOREIGN KEY (page, setting) REFERENCES page_settings (page, setting) ON DELETE CASCADE
    );

INSERT INTO
    page_setting_display (page, setting, session, is_visible)
VALUES
    ('inputs', 'content.rev_lights', 'practice', 0),
    ('inputs', 'content.rev_lights', 'race', 0),
    ('inputs', 'content.rev_lights', 'qualy', 0),
    ('inputs', 'content.gear_and_speed', 'practice', 0),
    ('inputs', 'content.gear_and_speed', 'race', 0),
    ('inputs', 'content.gear_and_speed', 'qualy', 0),
    ('inputs', 'content.input_bars', 'practice', 0),
    ('inputs', 'content.input_bars', 'race', 0),
    ('inputs', 'content.input_bars', 'qualy', 0),
    ('inputs', 'content.steering_wheel', 'practice', 0),
    ('inputs', 'content.steering_wheel', 'race', 0),
    ('inputs', 'content.steering_wheel', 'qualy', 0),
    ('inputs', 'content.boost_ers', 'practice', 0),
    ('inputs', 'content.boost_ers', 'race', 0),
    ('inputs', 'content.boost_ers', 'qualy', 0),
    ('inputs', 'content.corner_speed', 'practice', 0),
    ('inputs', 'content.corner_speed', 'race', 0),
    ('inputs', 'content.corner_speed', 'qualy', 0),
    -- STANDINGS
    -- Content Tab
    ('standings', 'content.position', 'practice', 0),
    ('standings', 'content.position', 'race', 0),
    ('standings', 'content.position', 'qualy', 0),
    ('standings', 'content.class_badge_color', 'practice', 0),
    ('standings', 'content.class_badge_color', 'race', 0),
    ('standings', 'content.class_badge_color', 'qualy', 0),
    ('standings', 'content.car_number', 'practice', 0),
    ('standings', 'content.car_number', 'race', 0),
    ('standings', 'content.car_number', 'qualy', 0),
    ('standings', 'content.team_name', 'practice', 0),
    ('standings', 'content.team_name', 'race', 0),
    ('standings', 'content.team_name', 'qualy', 0),
    ('standings', 'content.license', 'practice', 0),
    ('standings', 'content.license', 'race', 0),
    ('standings', 'content.license', 'qualy', 0),
    ('standings', 'content.irating', 'practice', 0),
    ('standings', 'content.irating', 'race', 0),
    ('standings', 'content.irating', 'qualy', 0),
    ('standings', 'content.car_brand', 'practice', 0),
    ('standings', 'content.car_brand', 'race', 0),
    ('standings', 'content.car_brand', 'qualy', 0),
    ('standings', 'content.interval', 'practice', 0),
    ('standings', 'content.interval', 'race', 0),
    ('standings', 'content.interval', 'qualy', 0),
    ('standings', 'content.fastest_lap_time', 'practice', 0),
    ('standings', 'content.fastest_lap_time', 'race', 0),
    ('standings', 'content.fastest_lap_time', 'qualy', 0),
    ('standings', 'content.gap', 'practice', 0),
    ('standings', 'content.gap', 'race', 0),
    ('standings', 'content.gap', 'qualy', 0),
    ('standings', 'content.lap_delta', 'practice', 0),
    ('standings', 'content.lap_delta', 'race', 0),
    ('standings', 'content.lap_delta', 'qualy', 0),
    ('standings', 'content.positions_gained', 'practice', 0),
    ('standings', 'content.positions_gained', 'race', 0),
    ('standings', 'content.positions_gained', 'qualy', 0),
    ('standings', 'content.black_flag', 'practice', 0),
    ('standings', 'content.black_flag', 'race', 0),
    ('standings', 'content.black_flag', 'qualy', 0),
    ('standings', 'content.driver_name', 'practice', 0),
    ('standings', 'content.driver_name', 'race', 0),
    ('standings', 'content.driver_name', 'qualy', 0),
    ('standings', 'content.pitstop_status', 'practice', 0),
    ('standings', 'content.pitstop_status', 'race', 0),
    ('standings', 'content.pitstop_status', 'qualy', 0),
    ('standings', 'content.time_in_pitlane', 'practice', 0),
    ('standings', 'content.time_in_pitlane', 'race', 0),
    ('standings', 'content.time_in_pitlane', 'qualy', 0),
    ('standings', 'content.relative_time', 'practice', 0),
    ('standings', 'content.relative_time', 'race', 0),
    ('standings', 'content.relative_time', 'qualy', 0),
    ('standings', 'content.time_in_pitbox', 'practice', 0),
    ('standings', 'content.time_in_pitbox', 'race', 0),
    ('standings', 'content.time_in_pitbox', 'qualy', 0),
    (
        'standings',
        'content.current_stint_length',
        'practice',
        0
    ),
    ('standings', 'content.current_stint_length', 'race', 0),
    ('standings', 'content.current_stint_length', 'qualy', 0),
    ('standings', 'content.joker_lap', 'practice', 0),
    ('standings', 'content.joker_lap', 'race', 0),
    ('standings', 'content.joker_lap', 'qualy', 0),
    ('standings', 'content.tire_compound', 'practice', 0),
    ('standings', 'content.tire_compound', 'race', 0),
    ('standings', 'content.tire_compound', 'qualy', 0),
    ('standings', 'content.driver_tags', 'practice', 0),
    ('standings', 'content.driver_tags', 'race', 0),
    ('standings', 'content.driver_tags', 'qualy', 0),
    ('standings', 'content.avg_5_laps', 'practice', 0),
    ('standings', 'content.avg_5_laps', 'race', 0),
    ('standings', 'content.avg_5_laps', 'qualy', 0),
    ('standings', 'content.avg_10_laps', 'practice', 0),
    ('standings', 'content.avg_10_laps', 'race', 0),
    ('standings', 'content.avg_10_laps', 'qualy', 0),
    ('standings', 'content.push_to_pass', 'practice', 0),
    ('standings', 'content.push_to_pass', 'race', 0),
    ('standings', 'content.push_to_pass', 'qualy', 0),
    ('standings', 'content.country_flag', 'practice', 0),
    ('standings', 'content.country_flag', 'race', 0),
    ('standings', 'content.country_flag', 'qualy', 0),
    -- Class Header Tab
    ('standings', 'class_header.class_name', 'practice', 0),
    ('standings', 'class_header.class_name', 'race', 0),
    ('standings', 'class_header.class_name', 'qualy', 0),
    (
        'standings',
        'class_header.drivers_in_class',
        'practice',
        0
    ),
    ('standings', 'class_header.drivers_in_class', 'race', 0),
    ('standings', 'class_header.drivers_in_class', 'qualy', 0),
    ('standings', 'class_header.class_sof', 'practice', 0),
    ('standings', 'class_header.class_sof', 'race', 0),
    ('standings', 'class_header.class_sof', 'qualy', 0),
    -- Header Tab
    ('standings', 'header.session_name', 'practice', 0),
    ('standings', 'header.session_name', 'race', 0),
    ('standings', 'header.session_name', 'qualy', 0),
    ('standings', 'header.event_type', 'practice', 0),
    ('standings', 'header.event_type', 'race', 0),
    ('standings', 'header.event_type', 'qualy', 0),
    ('standings', 'header.local_time_24h', 'practice', 0),
    ('standings', 'header.local_time_24h', 'race', 0),
    ('standings', 'header.local_time_24h', 'qualy', 0),
    ('standings', 'header.local_time_am_pm', 'practice', 0),
    ('standings', 'header.local_time_am_pm', 'race', 0),
    ('standings', 'header.local_time_am_pm', 'qualy', 0),
    ('standings', 'header.in_sim_time_24h', 'practice', 0),
    ('standings', 'header.in_sim_time_24h', 'race', 0),
    ('standings', 'header.in_sim_time_24h', 'qualy', 0),
    ('standings', 'header.in_sim_time_am_pm', 'practice', 0),
    ('standings', 'header.in_sim_time_am_pm', 'race', 0),
    ('standings', 'header.in_sim_time_am_pm', 'qualy', 0),
    ('standings', 'header.air_temp', 'practice', 0),
    ('standings', 'header.air_temp', 'race', 0),
    ('standings', 'header.air_temp', 'qualy', 0),
    ('standings', 'header.track_temp', 'practice', 0),
    ('standings', 'header.track_temp', 'race', 0),
    ('standings', 'header.track_temp', 'qualy', 0),
    ('standings', 'header.humidity', 'practice', 0),
    ('standings', 'header.humidity', 'race', 0),
    ('standings', 'header.humidity', 'qualy', 0),
    ('standings', 'header.fog_level', 'practice', 0),
    ('standings', 'header.fog_level', 'race', 0),
    ('standings', 'header.fog_level', 'qualy', 0),
    ('standings', 'header.time_remaining', 'practice', 0),
    ('standings', 'header.time_remaining', 'race', 0),
    ('standings', 'header.time_remaining', 'qualy', 0),
    ('standings', 'header.laps_remaining', 'practice', 0),
    ('standings', 'header.laps_remaining', 'race', 0),
    ('standings', 'header.laps_remaining', 'qualy', 0),
    ('standings', 'header.incident_count', 'practice', 0),
    ('standings', 'header.incident_count', 'race', 0),
    ('standings', 'header.incident_count', 'qualy', 0),
    ('standings', 'header.current_lap_time', 'practice', 0),
    ('standings', 'header.current_lap_time', 'race', 0),
    ('standings', 'header.current_lap_time', 'qualy', 0),
    (
        'standings',
        'header.session_best_lap_time',
        'practice',
        0
    ),
    ('standings', 'header.session_best_lap_time', 'race', 0),
    ('standings', 'header.session_best_lap_time', 'qualy', 0),
    ('standings', 'header.last_lap_time', 'practice', 0),
    ('standings', 'header.last_lap_time', 'race', 0),
    ('standings', 'header.last_lap_time', 'qualy', 0),
    (
        'standings',
        'header.last_lap_time_calculated',
        'practice',
        0
    ),
    (
        'standings',
        'header.last_lap_time_calculated',
        'race',
        0
    ),
    (
        'standings',
        'header.last_lap_time_calculated',
        'qualy',
        0
    ),
    ('standings', 'header.lap_delta_best', 'practice', 0),
    ('standings', 'header.lap_delta_best', 'race', 0),
    ('standings', 'header.lap_delta_best', 'qualy', 0),
    ('standings', 'header.lap_delta_optimal', 'practice', 0),
    ('standings', 'header.lap_delta_optimal', 'race', 0),
    ('standings', 'header.lap_delta_optimal', 'qualy', 0),
    (
        'standings',
        'header.lap_delta_session_best',
        'practice',
        0
    ),
    ('standings', 'header.lap_delta_session_best', 'race', 0),
    ('standings', 'header.lap_delta_session_best', 'qualy', 0),
    (
        'standings',
        'header.lap_delta_session_optimal',
        'practice',
        0
    ),
    (
        'standings',
        'header.lap_delta_session_optimal',
        'race',
        0
    ),
    (
        'standings',
        'header.lap_delta_session_optimal',
        'qualy',
        0
    ),
    (
        'standings',
        'header.lap_delta_session_last',
        'practice',
        0
    ),
    ('standings', 'header.lap_delta_session_last', 'race', 0),
    ('standings', 'header.lap_delta_session_last', 'qualy', 0),
    ('standings', 'header.brake_bias', 'practice', 0),
    ('standings', 'header.brake_bias', 'race', 0),
    ('standings', 'header.brake_bias', 'qualy', 0),
    ('standings', 'header.fuel_level', 'practice', 0),
    ('standings', 'header.fuel_level', 'race', 0),
    ('standings', 'header.fuel_level', 'qualy', 0),
    ('standings', 'header.water_temp', 'practice', 0),
    ('standings', 'header.water_temp', 'race', 0),
    ('standings', 'header.water_temp', 'qualy', 0),
    ('standings', 'header.oil_temp', 'practice', 0),
    ('standings', 'header.oil_temp', 'race', 0),
    ('standings', 'header.oil_temp', 'qualy', 0),
    ('standings', 'header.sof', 'practice', 0),
    ('standings', 'header.sof', 'race', 0),
    ('standings', 'header.sof', 'qualy', 0),
    (
        'standings',
        'header.current_stint_in_laps',
        'practice',
        0
    ),
    ('standings', 'header.current_stint_in_laps', 'race', 0),
    ('standings', 'header.current_stint_in_laps', 'qualy', 0),
    (
        'standings',
        'header.current_stint_in_time',
        'practice',
        0
    ),
    ('standings', 'header.current_stint_in_time', 'race', 0),
    ('standings', 'header.current_stint_in_time', 'qualy', 0),
    ('standings', 'header.rpm', 'practice', 0),
    ('standings', 'header.rpm', 'race', 0),
    ('standings', 'header.rpm', 'qualy', 0),
    ('standings', 'header.deploy_mode', 'practice', 0),
    ('standings', 'header.deploy_mode', 'race', 0),
    ('standings', 'header.deploy_mode', 'qualy', 0),
    ('standings', 'header.arb_front', 'practice', 0),
    ('standings', 'header.arb_front', 'race', 0),
    ('standings', 'header.arb_front', 'qualy', 0),
    ('standings', 'header.arb_rear', 'practice', 0),
    ('standings', 'header.arb_rear', 'race', 0),
    ('standings', 'header.arb_rear', 'qualy', 0),
    ('standings', 'header.abs', 'practice', 0),
    ('standings', 'header.abs', 'race', 0),
    ('standings', 'header.abs', 'qualy', 0),
    ('standings', 'header.tc_1', 'practice', 0),
    ('standings', 'header.tc_1', 'race', 0),
    ('standings', 'header.tc_1', 'qualy', 0),
    ('standings', 'header.tc_2', 'practice', 0),
    ('standings', 'header.tc_2', 'race', 0),
    ('standings', 'header.tc_2', 'qualy', 0),
    ('standings', 'header.weight_jacker', 'practice', 0),
    ('standings', 'header.weight_jacker', 'race', 0),
    ('standings', 'header.weight_jacker', 'qualy', 0),
    ('standings', 'header.rear_brake_valve', 'practice', 0),
    ('standings', 'header.rear_brake_valve', 'race', 0),
    ('standings', 'header.rear_brake_valve', 'qualy', 0),
    ('standings', 'header.precippitation', 'practice', 0),
    ('standings', 'header.precippitation', 'race', 0),
    ('standings', 'header.precippitation', 'qualy', 0),
    ('standings', 'header.track_wetness', 'practice', 0),
    ('standings', 'header.track_wetness', 'race', 0),
    ('standings', 'header.track_wetness', 'qualy', 0),
    (
        'standings',
        'header.weather_declared_wet',
        'practice',
        0
    ),
    ('standings', 'header.weather_declared_wet', 'race', 0),
    ('standings', 'header.weather_declared_wet', 'qualy', 0),
    ('standings', 'header.pit_time_loss', 'practice', 0),
    ('standings', 'header.pit_time_loss', 'race', 0),
    ('standings', 'header.pit_time_loss', 'qualy', 0),
    (
        'standings',
        'header.wind_direction_for_driver',
        'practice',
        0
    ),
    (
        'standings',
        'header.wind_direction_for_driver',
        'race',
        0
    ),
    (
        'standings',
        'header.wind_direction_for_driver',
        'qualy',
        0
    ),
    (
        'standings',
        'header.predicted_position_after_pit_stop',
        'practice',
        0
    ),
    (
        'standings',
        'header.predicted_position_after_pit_stop',
        'race',
        0
    ),
    (
        'standings',
        'header.predicted_position_after_pit_stop',
        'qualy',
        0
    ),
    ('standings', 'header.irating_and_gain', 'practice', 0),
    ('standings', 'header.irating_and_gain', 'race', 0),
    ('standings', 'header.irating_and_gain', 'qualy', 0),
    ('standings', 'header.push_to_pass', 'practice', 0),
    ('standings', 'header.push_to_pass', 'race', 0),
    ('standings', 'header.push_to_pass', 'qualy', 0),
    -- RELATIVE
    -- Content Tab
    ('relative', 'content.position', 'practice', 0),
    ('relative', 'content.position', 'race', 0),
    ('relative', 'content.position', 'qualy', 0),
    ('relative', 'content.class_badge_color', 'practice', 0),
    ('relative', 'content.class_badge_color', 'race', 0),
    ('relative', 'content.class_badge_color', 'qualy', 0),
    ('relative', 'content.driver_name', 'practice', 0),
    ('relative', 'content.driver_name', 'race', 0),
    ('relative', 'content.driver_name', 'qualy', 0),
    ('relative', 'content.license', 'practice', 0),
    ('relative', 'content.license', 'race', 0),
    ('relative', 'content.license', 'qualy', 0),
    ('relative', 'content.irating', 'practice', 0),
    ('relative', 'content.irating', 'race', 0),
    ('relative', 'content.irating', 'qualy', 0),
    ('relative', 'content.relative_time', 'practice', 0),
    ('relative', 'content.relative_time', 'race', 0),
    ('relative', 'content.relative_time', 'qualy', 0),
    ('relative', 'content.team_name', 'practice', 0),
    ('relative', 'content.team_name', 'race', 0),
    ('relative', 'content.team_name', 'qualy', 0),
    ('relative', 'content.car_brand', 'practice', 0),
    ('relative', 'content.car_brand', 'race', 0),
    ('relative', 'content.car_brand', 'qualy', 0),
    ('relative', 'content.intervals', 'practice', 0),
    ('relative', 'content.intervals', 'race', 0),
    ('relative', 'content.intervals', 'qualy', 0),
    ('relative', 'content.gap', 'practice', 0),
    ('relative', 'content.gap', 'race', 0),
    ('relative', 'content.gap', 'qualy', 0),
    ('relative', 'content.fastest_lap_time', 'practice', 0),
    ('relative', 'content.fastest_lap_time', 'race', 0),
    ('relative', 'content.fastest_lap_time', 'qualy', 0),
    ('relative', 'content.last_lap_time', 'practice', 0),
    ('relative', 'content.last_lap_time', 'race', 0),
    ('relative', 'content.last_lap_time', 'qualy', 0),
    ('relative', 'content.lap_delta', 'practice', 0),
    ('relative', 'content.lap_delta', 'race', 0),
    ('relative', 'content.lap_delta', 'qualy', 0),
    ('relative', 'content.pitstop_status', 'practice', 0),
    ('relative', 'content.pitstop_status', 'race', 0),
    ('relative', 'content.pitstop_status', 'qualy', 0),
    ('relative', 'content.time_in_pitlane', 'practice', 0),
    ('relative', 'content.time_in_pitlane', 'race', 0),
    ('relative', 'content.time_in_pitlane', 'qualy', 0),
    ('relative', 'content.time_in_pitbox', 'practice', 0),
    ('relative', 'content.time_in_pitbox', 'race', 0),
    ('relative', 'content.time_in_pitbox', 'qualy', 0),
    ('relative', 'content.current_stint_length', 'practice', 0),
    ('relative', 'content.current_stint_length', 'race', 0),
    ('relative', 'content.current_stint_length', 'qualy', 0),
    ('relative', 'content.positions_gained', 'practice', 0),
    ('relative', 'content.positions_gained', 'race', 0),
    ('relative', 'content.positions_gained', 'qualy', 0),
    ('relative', 'content.joker_lap', 'practice', 0),
    ('relative', 'content.joker_lap', 'race', 0),
    ('relative', 'content.joker_lap', 'qualy', 0),
    ('relative', 'content.tire_compound', 'practice', 0),
    ('relative', 'content.tire_compound', 'race', 0),
    ('relative', 'content.tire_compound', 'qualy', 0),
    ('relative', 'content.driver_tags', 'practice', 0),
    ('relative', 'content.driver_tags', 'race', 0),
    ('relative', 'content.driver_tags', 'qualy', 0),
    ('relative', 'content.black_flag', 'practice', 0),
    ('relative', 'content.black_flag', 'race', 0),
    ('relative', 'content.black_flag', 'qualy', 0),
    ('relative', 'content.avg_5_laps', 'practice', 0),
    ('relative', 'content.avg_5_laps', 'race', 0),
    ('relative', 'content.avg_5_laps', 'qualy', 0),
    ('relative', 'content.avg_10_laps', 'practice', 0),
    ('relative', 'content.avg_10_laps', 'race', 0),
    ('relative', 'content.avg_10_laps', 'qualy', 0),
    ('relative', 'content.push_to_pass', 'practice', 0),
    ('relative', 'content.push_to_pass', 'race', 0),
    ('relative', 'content.push_to_pass', 'qualy', 0),
    ('relative', 'content.country_flag', 'practice', 0),
    ('relative', 'content.country_flag', 'race', 0),
    ('relative', 'content.country_flag', 'qualy', 0),
    -- Header Tab
    ('relative', 'header.session_name', 'practice', 0),
    ('relative', 'header.session_name', 'race', 0),
    ('relative', 'header.session_name', 'qualy', 0),
    ('relative', 'header.event_type', 'practice', 0),
    ('relative', 'header.event_type', 'race', 0),
    ('relative', 'header.event_type', 'qualy', 0),
    ('relative', 'header.local_time_24h', 'practice', 0),
    ('relative', 'header.local_time_24h', 'race', 0),
    ('relative', 'header.local_time_24h', 'qualy', 0),
    ('relative', 'header.local_time_am_pm', 'practice', 0),
    ('relative', 'header.local_time_am_pm', 'race', 0),
    ('relative', 'header.local_time_am_pm', 'qualy', 0),
    ('relative', 'header.in_sim_time_24h', 'practice', 0),
    ('relative', 'header.in_sim_time_24h', 'race', 0),
    ('relative', 'header.in_sim_time_24h', 'qualy', 0),
    ('relative', 'header.in_sim_time_am_pm', 'practice', 0),
    ('relative', 'header.in_sim_time_am_pm', 'race', 0),
    ('relative', 'header.in_sim_time_am_pm', 'qualy', 0),
    ('relative', 'header.air_temp', 'practice', 0),
    ('relative', 'header.air_temp', 'race', 0),
    ('relative', 'header.air_temp', 'qualy', 0),
    ('relative', 'header.track_temp', 'practice', 0),
    ('relative', 'header.track_temp', 'race', 0),
    ('relative', 'header.track_temp', 'qualy', 0),
    ('relative', 'header.humidity', 'practice', 0),
    ('relative', 'header.humidity', 'race', 0),
    ('relative', 'header.humidity', 'qualy', 0),
    ('relative', 'header.fog_level', 'practice', 0),
    ('relative', 'header.fog_level', 'race', 0),
    ('relative', 'header.fog_level', 'qualy', 0),
    ('relative', 'header.time_remaining', 'practice', 0),
    ('relative', 'header.time_remaining', 'race', 0),
    ('relative', 'header.time_remaining', 'qualy', 0),
    ('relative', 'header.laps_remaining', 'practice', 0),
    ('relative', 'header.laps_remaining', 'race', 0),
    ('relative', 'header.laps_remaining', 'qualy', 0),
    ('relative', 'header.incident_count', 'practice', 0),
    ('relative', 'header.incident_count', 'race', 0),
    ('relative', 'header.incident_count', 'qualy', 0),
    ('relative', 'header.current_lap_time', 'practice', 0),
    ('relative', 'header.current_lap_time', 'race', 0),
    ('relative', 'header.current_lap_time', 'qualy', 0),
    ('relative', 'header.session_best_lap_time', 'practice', 0),
    ('relative', 'header.session_best_lap_time', 'race', 0),
    ('relative', 'header.session_best_lap_time', 'qualy', 0),
    ('relative', 'header.last_lap_time', 'practice', 0),
    ('relative', 'header.last_lap_time', 'race', 0),
    ('relative', 'header.last_lap_time', 'qualy', 0),
    ('relative', 'header.last_lap_time_calculated', 'practice', 0),
    ('relative', 'header.last_lap_time_calculated', 'race', 0),
    ('relative', 'header.last_lap_time_calculated', 'qualy', 0),
    ('relative', 'header.lap_delta_best', 'practice', 0),
    ('relative', 'header.lap_delta_best', 'race', 0),
    ('relative', 'header.lap_delta_best', 'qualy', 0),
    ('relative', 'header.lap_delta_optimal', 'practice', 0),
    ('relative', 'header.lap_delta_optimal', 'race', 0),
    ('relative', 'header.lap_delta_optimal', 'qualy', 0),
    ('relative', 'header.lap_delta_session_best', 'practice', 0),
    ('relative', 'header.lap_delta_session_best', 'race', 0),
    ('relative', 'header.lap_delta_session_best', 'qualy', 0),
    ('relative', 'header.lap_delta_session_optimal', 'practice', 0),
    ('relative', 'header.lap_delta_session_optimal', 'race', 0),
    ('relative', 'header.lap_delta_session_optimal', 'qualy', 0),
    ('relative', 'header.lap_delta_session_last', 'practice', 0),
    ('relative', 'header.lap_delta_session_last', 'race', 0),
    ('relative', 'header.lap_delta_session_last', 'qualy', 0),
    ('relative', 'header.brake_bias', 'practice', 0),
    ('relative', 'header.brake_bias', 'race', 0),
    ('relative', 'header.brake_bias', 'qualy', 0),
    ('relative', 'header.fuel_level', 'practice', 0),
    ('relative', 'header.fuel_level', 'race', 0),
    ('relative', 'header.fuel_level', 'qualy', 0),
    ('relative', 'header.water_temp', 'practice', 0),
    ('relative', 'header.water_temp', 'race', 0),
    ('relative', 'header.water_temp', 'qualy', 0),
    ('relative', 'header.oil_temp', 'practice', 0),
    ('relative', 'header.oil_temp', 'race', 0),
    ('relative', 'header.oil_temp', 'qualy', 0),
    ('relative', 'header.sof', 'practice', 0),
    ('relative', 'header.sof', 'race', 0),
    ('relative', 'header.sof', 'qualy', 0),
    ('relative', 'header.current_stint_in_laps', 'practice', 0),
    ('relative', 'header.current_stint_in_laps', 'race', 0),
    ('relative', 'header.current_stint_in_laps', 'qualy', 0),
    ('relative', 'header.current_stint_in_time', 'practice', 0),
    ('relative', 'header.current_stint_in_time', 'race', 0),
    ('relative', 'header.current_stint_in_time', 'qualy', 0),
    ('relative', 'header.rpm', 'practice', 0),
    ('relative', 'header.rpm', 'race', 0),
    ('relative', 'header.rpm', 'qualy', 0),
    ('relative', 'header.deploy_mode', 'practice', 0),
    ('relative', 'header.deploy_mode', 'race', 0),
    ('relative', 'header.deploy_mode', 'qualy', 0),
    ('relative', 'header.arb_front', 'practice', 0),
    ('relative', 'header.arb_front', 'race', 0),
    ('relative', 'header.arb_front', 'qualy', 0),
    ('relative', 'header.arb_rear', 'practice', 0),
    ('relative', 'header.arb_rear', 'race', 0),
    ('relative', 'header.arb_rear', 'qualy', 0),
    ('relative', 'header.abs', 'practice', 0),
    ('relative', 'header.abs', 'race', 0),
    ('relative', 'header.abs', 'qualy', 0),
    ('relative', 'header.tc_1', 'practice', 0),
    ('relative', 'header.tc_1', 'race', 0),
    ('relative', 'header.tc_1', 'qualy', 0),
    ('relative', 'header.tc_2', 'practice', 0),
    ('relative', 'header.tc_2', 'race', 0),
    ('relative', 'header.tc_2', 'qualy', 0),
    ('relative', 'header.weight_jacker', 'practice', 0),
    ('relative', 'header.weight_jacker', 'race', 0),
    ('relative', 'header.weight_jacker', 'qualy', 0),
    ('relative', 'header.rear_brake_valve', 'practice', 0),
    ('relative', 'header.rear_brake_valve', 'race', 0),
    ('relative', 'header.rear_brake_valve', 'qualy', 0),
    ('relative', 'header.precippitation', 'practice', 0),
    ('relative', 'header.precippitation', 'race', 0),
    ('relative', 'header.precippitation', 'qualy', 0),
    ('relative', 'header.track_wetness', 'practice', 0),
    ('relative', 'header.track_wetness', 'race', 0),
    ('relative', 'header.track_wetness', 'qualy', 0),
    ('relative', 'header.weather_declared_wet', 'practice', 0),
    ('relative', 'header.weather_declared_wet', 'race', 0),
    ('relative', 'header.weather_declared_wet', 'qualy', 0),
    ('relative', 'header.pit_time_loss', 'practice', 0),
    ('relative', 'header.pit_time_loss', 'race', 0),
    ('relative', 'header.pit_time_loss', 'qualy', 0),
    ('relative', 'header.wind_direction_for_driver', 'practice', 0),
    ('relative', 'header.wind_direction_for_driver', 'race', 0),
    ('relative', 'header.wind_direction_for_driver', 'qualy', 0),
    (
        'relative',
        'header.predicted_position_after_pit_stop',
        'practice',
        0
    ),
    (
        'relative',
        'header.predicted_position_after_pit_stop',
        'race',
        0
    ),
    (
        'relative',
        'header.predicted_position_after_pit_stop',
        'qualy',
        0
    ),
    ('relative', 'header.irating_and_gain', 'practice', 0),
    ('relative', 'header.irating_and_gain', 'race', 0),
    ('relative', 'header.irating_and_gain', 'qualy', 0),
    ('relative', 'header.push_to_pass', 'practice', 0),
    ('relative', 'header.push_to_pass', 'race', 0),
    ('relative', 'header.push_to_pass', 'qualy', 0),
    -- Footer Tab
    ('relative', 'footer.session_name', 'practice', 0),
    ('relative', 'footer.session_name', 'race', 0),
    ('relative', 'footer.session_name', 'qualy', 0),
    ('relative', 'footer.event_type', 'practice', 0),
    ('relative', 'footer.event_type', 'race', 0),
    ('relative', 'footer.event_type', 'qualy', 0),
    ('relative', 'footer.local_time_24h', 'practice', 0),
    ('relative', 'footer.local_time_24h', 'race', 0),
    ('relative', 'footer.local_time_24h', 'qualy', 0),
    ('relative', 'footer.local_time_am_pm', 'practice', 0),
    ('relative', 'footer.local_time_am_pm', 'race', 0),
    ('relative', 'footer.local_time_am_pm', 'qualy', 0),
    ('relative', 'footer.in_sim_time_24h', 'practice', 0),
    ('relative', 'footer.in_sim_time_24h', 'race', 0),
    ('relative', 'footer.in_sim_time_24h', 'qualy', 0),
    ('relative', 'footer.in_sim_time_am_pm', 'practice', 0),
    ('relative', 'footer.in_sim_time_am_pm', 'race', 0),
    ('relative', 'footer.in_sim_time_am_pm', 'qualy', 0),
    ('relative', 'footer.air_temp', 'practice', 0),
    ('relative', 'footer.air_temp', 'race', 0),
    ('relative', 'footer.air_temp', 'qualy', 0),
    ('relative', 'footer.track_temp', 'practice', 0),
    ('relative', 'footer.track_temp', 'race', 0),
    ('relative', 'footer.track_temp', 'qualy', 0),
    ('relative', 'footer.humidity', 'practice', 0),
    ('relative', 'footer.humidity', 'race', 0),
    ('relative', 'footer.humidity', 'qualy', 0),
    ('relative', 'footer.fog_level', 'practice', 0),
    ('relative', 'footer.fog_level', 'race', 0),
    ('relative', 'footer.fog_level', 'qualy', 0),
    ('relative', 'footer.time_remaining', 'practice', 0),
    ('relative', 'footer.time_remaining', 'race', 0),
    ('relative', 'footer.time_remaining', 'qualy', 0),
    ('relative', 'footer.laps_remaining', 'practice', 0),
    ('relative', 'footer.laps_remaining', 'race', 0),
    ('relative', 'footer.laps_remaining', 'qualy', 0),
    ('relative', 'footer.incident_count', 'practice', 0),
    ('relative', 'footer.incident_count', 'race', 0),
    ('relative', 'footer.incident_count', 'qualy', 0),
    ('relative', 'footer.current_lap_time', 'practice', 0),
    ('relative', 'footer.current_lap_time', 'race', 0),
    ('relative', 'footer.current_lap_time', 'qualy', 0),
    ('relative', 'footer.session_best_lap_time', 'practice', 0),
    ('relative', 'footer.session_best_lap_time', 'race', 0),
    ('relative', 'footer.session_best_lap_time', 'qualy', 0),
    ('relative', 'footer.last_lap_time', 'practice', 0),
    ('relative', 'footer.last_lap_time', 'race', 0),
    ('relative', 'footer.last_lap_time', 'qualy', 0),
    ('relative', 'footer.last_lap_time_calculated', 'practice', 0),
    ('relative', 'footer.last_lap_time_calculated', 'race', 0),
    ('relative', 'footer.last_lap_time_calculated', 'qualy', 0),
    ('relative', 'footer.lap_delta_best', 'practice', 0),
    ('relative', 'footer.lap_delta_best', 'race', 0),
    ('relative', 'footer.lap_delta_best', 'qualy', 0),
    ('relative', 'footer.lap_delta_optimal', 'practice', 0),
    ('relative', 'footer.lap_delta_optimal', 'race', 0),
    ('relative', 'footer.lap_delta_optimal', 'qualy', 0),
    ('relative', 'footer.lap_delta_session_best', 'practice', 0),
    ('relative', 'footer.lap_delta_session_best', 'race', 0),
    ('relative', 'footer.lap_delta_session_best', 'qualy', 0),
    ('relative', 'footer.lap_delta_session_optimal', 'practice', 0),
    ('relative', 'footer.lap_delta_session_optimal', 'race', 0),
    ('relative', 'footer.lap_delta_session_optimal', 'qualy', 0),
    ('relative', 'footer.lap_delta_session_last', 'practice', 0),
    ('relative', 'footer.lap_delta_session_last', 'race', 0),
    ('relative', 'footer.lap_delta_session_last', 'qualy', 0),
    ('relative', 'footer.brake_bias', 'practice', 0),
    ('relative', 'footer.brake_bias', 'race', 0),
    ('relative', 'footer.brake_bias', 'qualy', 0),
    ('relative', 'footer.fuel_level', 'practice', 0),
    ('relative', 'footer.fuel_level', 'race', 0),
    ('relative', 'footer.fuel_level', 'qualy', 0),
    ('relative', 'footer.water_temp', 'practice', 0),
    ('relative', 'footer.water_temp', 'race', 0),
    ('relative', 'footer.water_temp', 'qualy', 0),
    ('relative', 'footer.oil_temp', 'practice', 0),
    ('relative', 'footer.oil_temp', 'race', 0),
    ('relative', 'footer.oil_temp', 'qualy', 0),
    ('relative', 'footer.sof', 'practice', 0),
    ('relative', 'footer.sof', 'race', 0),
    ('relative', 'footer.sof', 'qualy', 0),
    ('relative', 'footer.current_stint_in_laps', 'practice', 0),
    ('relative', 'footer.current_stint_in_laps', 'race', 0),
    ('relative', 'footer.current_stint_in_laps', 'qualy', 0),
    ('relative', 'footer.current_stint_in_time', 'practice', 0),
    ('relative', 'footer.current_stint_in_time', 'race', 0),
    ('relative', 'footer.current_stint_in_time', 'qualy', 0),
    ('relative', 'footer.rpm', 'practice', 0),
    ('relative', 'footer.rpm', 'race', 0),
    ('relative', 'footer.rpm', 'qualy', 0),
    ('relative', 'footer.deploy_mode', 'practice', 0),
    ('relative', 'footer.deploy_mode', 'race', 0),
    ('relative', 'footer.deploy_mode', 'qualy', 0),
    ('relative', 'footer.arb_front', 'practice', 0),
    ('relative', 'footer.arb_front', 'race', 0),
    ('relative', 'footer.arb_front', 'qualy', 0),
    ('relative', 'footer.arb_rear', 'practice', 0),
    ('relative', 'footer.arb_rear', 'race', 0),
    ('relative', 'footer.arb_rear', 'qualy', 0),
    ('relative', 'footer.abs', 'practice', 0),
    ('relative', 'footer.abs', 'race', 0),
    ('relative', 'footer.abs', 'qualy', 0),
    ('relative', 'footer.tc_1', 'practice', 0),
    ('relative', 'footer.tc_1', 'race', 0),
    ('relative', 'footer.tc_1', 'qualy', 0),
    ('relative', 'footer.tc_2', 'practice', 0),
    ('relative', 'footer.tc_2', 'race', 0),
    ('relative', 'footer.tc_2', 'qualy', 0),
    ('relative', 'footer.weight_jacker', 'practice', 0),
    ('relative', 'footer.weight_jacker', 'race', 0),
    ('relative', 'footer.weight_jacker', 'qualy', 0),
    ('relative', 'footer.rear_brake_valve', 'practice', 0),
    ('relative', 'footer.rear_brake_valve', 'race', 0),
    ('relative', 'footer.rear_brake_valve', 'qualy', 0),
    ('relative', 'footer.precippitation', 'practice', 0),
    ('relative', 'footer.precippitation', 'race', 0),
    ('relative', 'footer.precippitation', 'qualy', 0),
    ('relative', 'footer.track_wetness', 'practice', 0),
    ('relative', 'footer.track_wetness', 'race', 0),
    ('relative', 'footer.track_wetness', 'qualy', 0),
    ('relative', 'footer.weather_declared_wet', 'practice', 0),
    ('relative', 'footer.weather_declared_wet', 'race', 0),
    ('relative', 'footer.weather_declared_wet', 'qualy', 0),
    ('relative', 'footer.pit_time_loss', 'practice', 0),
    ('relative', 'footer.pit_time_loss', 'race', 0),
    ('relative', 'footer.pit_time_loss', 'qualy', 0),
    ('relative', 'footer.wind_direction_for_driver', 'practice', 0),
    ('relative', 'footer.wind_direction_for_driver', 'race', 0),
    ('relative', 'footer.wind_direction_for_driver', 'qualy', 0),
    (
        'relative',
        'footer.predicted_position_after_pit_stop',
        'practice',
        0
    ),
    (
        'relative',
        'footer.predicted_position_after_pit_stop',
        'race',
        0
    ),
    (
        'relative',
        'footer.predicted_position_after_pit_stop',
        'qualy',
        0
    ),
    ('relative', 'footer.irating_and_gain', 'practice', 0),
    ('relative', 'footer.irating_and_gain', 'race', 0),
    ('relative', 'footer.irating_and_gain', 'qualy', 0),
    ('relative', 'footer.push_to_pass', 'practice', 0),
    ('relative', 'footer.push_to_pass', 'race', 0),
    ('relative', 'footer.push_to_pass', 'qualy', 0),
    -- FUEL CALCULATOR
    -- Content Tab
    ('fuel_calculator', 'content.average_last_5_laps', 'practice', 0),
    ('fuel_calculator', 'content.average_last_5_laps', 'race', 0),
    ('fuel_calculator', 'content.average_last_5_laps', 'qualy', 0),
    ('fuel_calculator', 'content.last_lap', 'practice', 0),
    ('fuel_calculator', 'content.last_lap', 'race', 0),
    ('fuel_calculator', 'content.last_lap', 'qualy', 0),
    ('fuel_calculator', 'content.qualy_lap', 'practice', 0),
    ('fuel_calculator', 'content.qualy_lap', 'race', 0),
    ('fuel_calculator', 'content.qualy_lap', 'qualy', 0),
    ('fuel_calculator', 'content.average_10_laps', 'practice', 0),
    ('fuel_calculator', 'content.average_10_laps', 'race', 0),
    ('fuel_calculator', 'content.average_10_laps', 'qualy', 0),
    (
        'fuel_calculator',
        'content.minimal_usage_in_session',
        'practice',
        0
    ),
    ('fuel_calculator', 'content.minimal_usage_in_session', 'race', 0),
    ('fuel_calculator', 'content.minimal_usage_in_session', 'qualy', 0),
    (
        'fuel_calculator',
        'content.maximum_usage_in_session',
        'practice',
        0
    ),
    ('fuel_calculator', 'content.maximum_usage_in_session', 'race', 0),
    ('fuel_calculator', 'content.maximum_usage_in_session', 'qualy', 0),
    -- Header Tab
    ('fuel_calculator', 'header.session_name', 'practice', 0),
    ('fuel_calculator', 'header.session_name', 'race', 0),
    ('fuel_calculator', 'header.session_name', 'qualy', 0),
    ('fuel_calculator', 'header.event_type', 'practice', 0),
    ('fuel_calculator', 'header.event_type', 'race', 0),
    ('fuel_calculator', 'header.event_type', 'qualy', 0),
    ('fuel_calculator', 'header.local_time_24h', 'practice', 0),
    ('fuel_calculator', 'header.local_time_24h', 'race', 0),
    ('fuel_calculator', 'header.local_time_24h', 'qualy', 0),
    ('fuel_calculator', 'header.local_time_am_pm', 'practice', 0),
    ('fuel_calculator', 'header.local_time_am_pm', 'race', 0),
    ('fuel_calculator', 'header.local_time_am_pm', 'qualy', 0),
    ('fuel_calculator', 'header.in_sim_time_24h', 'practice', 0),
    ('fuel_calculator', 'header.in_sim_time_24h', 'race', 0),
    ('fuel_calculator', 'header.in_sim_time_24h', 'qualy', 0),
    ('fuel_calculator', 'header.in_sim_time_am_pm', 'practice', 0),
    ('fuel_calculator', 'header.in_sim_time_am_pm', 'race', 0),
    ('fuel_calculator', 'header.in_sim_time_am_pm', 'qualy', 0),
    ('fuel_calculator', 'header.air_temp', 'practice', 0),
    ('fuel_calculator', 'header.air_temp', 'race', 0),
    ('fuel_calculator', 'header.air_temp', 'qualy', 0),
    ('fuel_calculator', 'header.track_temp', 'practice', 0),
    ('fuel_calculator', 'header.track_temp', 'race', 0),
    ('fuel_calculator', 'header.track_temp', 'qualy', 0),
    ('fuel_calculator', 'header.humidity', 'practice', 0),
    ('fuel_calculator', 'header.humidity', 'race', 0),
    ('fuel_calculator', 'header.humidity', 'qualy', 0),
    ('fuel_calculator', 'header.fog_level', 'practice', 0),
    ('fuel_calculator', 'header.fog_level', 'race', 0),
    ('fuel_calculator', 'header.fog_level', 'qualy', 0),
    ('fuel_calculator', 'header.time_remaining', 'practice', 0),
    ('fuel_calculator', 'header.time_remaining', 'race', 0),
    ('fuel_calculator', 'header.time_remaining', 'qualy', 0),
    ('fuel_calculator', 'header.laps_remaining', 'practice', 0),
    ('fuel_calculator', 'header.laps_remaining', 'race', 0),
    ('fuel_calculator', 'header.laps_remaining', 'qualy', 0),
    ('fuel_calculator', 'header.incident_count', 'practice', 0),
    ('fuel_calculator', 'header.incident_count', 'race', 0),
    ('fuel_calculator', 'header.incident_count', 'qualy', 0),
    ('fuel_calculator', 'header.current_lap_time', 'practice', 0),
    ('fuel_calculator', 'header.current_lap_time', 'race', 0),
    ('fuel_calculator', 'header.current_lap_time', 'qualy', 0),
    (
        'fuel_calculator',
        'header.session_best_lap_time',
        'practice',
        0
    ),
    ('fuel_calculator', 'header.session_best_lap_time', 'race', 0),
    ('fuel_calculator', 'header.session_best_lap_time', 'qualy', 0),
    ('fuel_calculator', 'header.last_lap_time', 'practice', 0),
    ('fuel_calculator', 'header.last_lap_time', 'race', 0),
    ('fuel_calculator', 'header.last_lap_time', 'qualy', 0),
    (
        'fuel_calculator',
        'header.last_lap_time_calculated',
        'practice',
        0
    ),
    ('fuel_calculator', 'header.last_lap_time_calculated', 'race', 0),
    (
        'fuel_calculator',
        'header.last_lap_time_calculated',
        'qualy',
        0
    ),
    ('fuel_calculator', 'header.lap_delta_best', 'practice', 0),
    ('fuel_calculator', 'header.lap_delta_best', 'race', 0),
    ('fuel_calculator', 'header.lap_delta_best', 'qualy', 0),
    ('fuel_calculator', 'header.lap_delta_optimal', 'practice', 0),
    ('fuel_calculator', 'header.lap_delta_optimal', 'race', 0),
    ('fuel_calculator', 'header.lap_delta_optimal', 'qualy', 0),
    (
        'fuel_calculator',
        'header.lap_delta_session_best',
        'practice',
        0
    ),
    ('fuel_calculator', 'header.lap_delta_session_best', 'race', 0),
    ('fuel_calculator', 'header.lap_delta_session_best', 'qualy', 0),
    (
        'fuel_calculator',
        'header.lap_delta_session_optimal',
        'practice',
        0
    ),
    (
        'fuel_calculator',
        'header.lap_delta_session_optimal',
        'race',
        0
    ),
    (
        'fuel_calculator',
        'header.lap_delta_session_optimal',
        'qualy',
        0
    ),
    (
        'fuel_calculator',
        'header.lap_delta_session_last',
        'practice',
        0
    ),
    ('fuel_calculator', 'header.lap_delta_session_last', 'race', 0),
    ('fuel_calculator', 'header.lap_delta_session_last', 'qualy', 0),
    ('fuel_calculator', 'header.brake_bias', 'practice', 0),
    ('fuel_calculator', 'header.brake_bias', 'race', 0),
    ('fuel_calculator', 'header.brake_bias', 'qualy', 0),
    ('fuel_calculator', 'header.fuel_level', 'practice', 0),
    ('fuel_calculator', 'header.fuel_level', 'race', 0),
    ('fuel_calculator', 'header.fuel_level', 'qualy', 0),
    ('fuel_calculator', 'header.water_temp', 'practice', 0),
    ('fuel_calculator', 'header.water_temp', 'race', 0),
    ('fuel_calculator', 'header.water_temp', 'qualy', 0),
    ('fuel_calculator', 'header.oil_temp', 'practice', 0),
    ('fuel_calculator', 'header.oil_temp', 'race', 0),
    ('fuel_calculator', 'header.oil_temp', 'qualy', 0),
    ('fuel_calculator', 'header.sof', 'practice', 0),
    ('fuel_calculator', 'header.sof', 'race', 0),
    ('fuel_calculator', 'header.sof', 'qualy', 0),
    ('fuel_calculator', 'header.current_stint_in_laps', 'practice', 0),
    ('fuel_calculator', 'header.current_stint_in_laps', 'race', 0),
    ('fuel_calculator', 'header.current_stint_in_laps', 'qualy', 0),
    ('fuel_calculator', 'header.current_stint_in_time', 'practice', 0),
    ('fuel_calculator', 'header.current_stint_in_time', 'race', 0),
    ('fuel_calculator', 'header.current_stint_in_time', 'qualy', 0),
    ('fuel_calculator', 'header.rpm', 'practice', 0),
    ('fuel_calculator', 'header.rpm', 'race', 0),
    ('fuel_calculator', 'header.rpm', 'qualy', 0),
    ('fuel_calculator', 'header.deploy_mode', 'practice', 0),
    ('fuel_calculator', 'header.deploy_mode', 'race', 0),
    ('fuel_calculator', 'header.deploy_mode', 'qualy', 0),
    ('fuel_calculator', 'header.arb_front', 'practice', 0),
    ('fuel_calculator', 'header.arb_front', 'race', 0),
    ('fuel_calculator', 'header.arb_front', 'qualy', 0),
    ('fuel_calculator', 'header.arb_rear', 'practice', 0),
    ('fuel_calculator', 'header.arb_rear', 'race', 0),
    ('fuel_calculator', 'header.arb_rear', 'qualy', 0),
    ('fuel_calculator', 'header.abs', 'practice', 0),
    ('fuel_calculator', 'header.abs', 'race', 0),
    ('fuel_calculator', 'header.abs', 'qualy', 0),
    ('fuel_calculator', 'header.tc_1', 'practice', 0),
    ('fuel_calculator', 'header.tc_1', 'race', 0),
    ('fuel_calculator', 'header.tc_1', 'qualy', 0),
    ('fuel_calculator', 'header.tc_2', 'practice', 0),
    ('fuel_calculator', 'header.tc_2', 'race', 0),
    ('fuel_calculator', 'header.tc_2', 'qualy', 0),
    ('fuel_calculator', 'header.weight_jacker', 'practice', 0),
    ('fuel_calculator', 'header.weight_jacker', 'race', 0),
    ('fuel_calculator', 'header.weight_jacker', 'qualy', 0),
    ('fuel_calculator', 'header.rear_brake_valve', 'practice', 0),
    ('fuel_calculator', 'header.rear_brake_valve', 'race', 0),
    ('fuel_calculator', 'header.rear_brake_valve', 'qualy', 0),
    ('fuel_calculator', 'header.precippitation', 'practice', 0),
    ('fuel_calculator', 'header.precippitation', 'race', 0),
    ('fuel_calculator', 'header.precippitation', 'qualy', 0),
    ('fuel_calculator', 'header.track_wetness', 'practice', 0),
    ('fuel_calculator', 'header.track_wetness', 'race', 0),
    ('fuel_calculator', 'header.track_wetness', 'qualy', 0),
    ('fuel_calculator', 'header.weather_declared_wet', 'practice', 0),
    ('fuel_calculator', 'header.weather_declared_wet', 'race', 0),
    ('fuel_calculator', 'header.weather_declared_wet', 'qualy', 0),
    ('fuel_calculator', 'header.pit_time_loss', 'practice', 0),
    ('fuel_calculator', 'header.pit_time_loss', 'race', 0),
    ('fuel_calculator', 'header.pit_time_loss', 'qualy', 0),
    (
        'fuel_calculator',
        'header.wind_direction_for_driver',
        'practice',
        0
    ),
    ('fuel_calculator', 'header.wind_direction_for_driver', 'race', 0),
    ('fuel_calculator', 'header.wind_direction_for_driver', 'qualy', 0),
    (
        'fuel_calculator',
        'header.predicted_position_after_pit_stop',
        'practice',
        0
    ),
    (
        'fuel_calculator',
        'header.predicted_position_after_pit_stop',
        'race',
        0
    ),
    (
        'fuel_calculator',
        'header.predicted_position_after_pit_stop',
        'qualy',
        0
    ),
    ('fuel_calculator', 'header.irating_and_gain', 'practice', 0),
    ('fuel_calculator', 'header.irating_and_gain', 'race', 0),
    ('fuel_calculator', 'header.irating_and_gain', 'qualy', 0),
    ('fuel_calculator', 'header.push_to_pass', 'practice', 0),
    ('fuel_calculator', 'header.push_to_pass', 'race', 0),
    ('fuel_calculator', 'header.push_to_pass', 'qualy', 0),
    -- Footer Tab
    ('fuel_calculator', 'footer.session_name', 'practice', 0),
    ('fuel_calculator', 'footer.session_name', 'race', 0),
    ('fuel_calculator', 'footer.session_name', 'qualy', 0),
    ('fuel_calculator', 'footer.event_type', 'practice', 0),
    ('fuel_calculator', 'footer.event_type', 'race', 0),
    ('fuel_calculator', 'footer.event_type', 'qualy', 0),
    ('fuel_calculator', 'footer.local_time_24h', 'practice', 0),
    ('fuel_calculator', 'footer.local_time_24h', 'race', 0),
    ('fuel_calculator', 'footer.local_time_24h', 'qualy', 0),
    ('fuel_calculator', 'footer.local_time_am_pm', 'practice', 0),
    ('fuel_calculator', 'footer.local_time_am_pm', 'race', 0),
    ('fuel_calculator', 'footer.local_time_am_pm', 'qualy', 0),
    ('fuel_calculator', 'footer.in_sim_time_24h', 'practice', 0),
    ('fuel_calculator', 'footer.in_sim_time_24h', 'race', 0),
    ('fuel_calculator', 'footer.in_sim_time_24h', 'qualy', 0),
    ('fuel_calculator', 'footer.in_sim_time_am_pm', 'practice', 0),
    ('fuel_calculator', 'footer.in_sim_time_am_pm', 'race', 0),
    ('fuel_calculator', 'footer.in_sim_time_am_pm', 'qualy', 0),
    ('fuel_calculator', 'footer.air_temp', 'practice', 0),
    ('fuel_calculator', 'footer.air_temp', 'race', 0),
    ('fuel_calculator', 'footer.air_temp', 'qualy', 0),
    ('fuel_calculator', 'footer.track_temp', 'practice', 0),
    ('fuel_calculator', 'footer.track_temp', 'race', 0),
    ('fuel_calculator', 'footer.track_temp', 'qualy', 0),
    ('fuel_calculator', 'footer.humidity', 'practice', 0),
    ('fuel_calculator', 'footer.humidity', 'race', 0),
    ('fuel_calculator', 'footer.humidity', 'qualy', 0),
    ('fuel_calculator', 'footer.fog_level', 'practice', 0),
    ('fuel_calculator', 'footer.fog_level', 'race', 0),
    ('fuel_calculator', 'footer.fog_level', 'qualy', 0),
    ('fuel_calculator', 'footer.time_remaining', 'practice', 0),
    ('fuel_calculator', 'footer.time_remaining', 'race', 0),
    ('fuel_calculator', 'footer.time_remaining', 'qualy', 0),
    ('fuel_calculator', 'footer.laps_remaining', 'practice', 0),
    ('fuel_calculator', 'footer.laps_remaining', 'race', 0),
    ('fuel_calculator', 'footer.laps_remaining', 'qualy', 0),
    ('fuel_calculator', 'footer.incident_count', 'practice', 0),
    ('fuel_calculator', 'footer.incident_count', 'race', 0),
    ('fuel_calculator', 'footer.incident_count', 'qualy', 0),
    ('fuel_calculator', 'footer.current_lap_time', 'practice', 0),
    ('fuel_calculator', 'footer.current_lap_time', 'race', 0),
    ('fuel_calculator', 'footer.current_lap_time', 'qualy', 0),
    (
        'fuel_calculator',
        'footer.session_best_lap_time',
        'practice',
        0
    ),
    ('fuel_calculator', 'footer.session_best_lap_time', 'race', 0),
    ('fuel_calculator', 'footer.session_best_lap_time', 'qualy', 0),
    ('fuel_calculator', 'footer.last_lap_time', 'practice', 0),
    ('fuel_calculator', 'footer.last_lap_time', 'race', 0),
    ('fuel_calculator', 'footer.last_lap_time', 'qualy', 0),
    (
        'fuel_calculator',
        'footer.last_lap_time_calculated',
        'practice',
        0
    ),
    ('fuel_calculator', 'footer.last_lap_time_calculated', 'race', 0),
    (
        'fuel_calculator',
        'footer.last_lap_time_calculated',
        'qualy',
        0
    ),
    ('fuel_calculator', 'footer.lap_delta_best', 'practice', 0),
    ('fuel_calculator', 'footer.lap_delta_best', 'race', 0),
    ('fuel_calculator', 'footer.lap_delta_best', 'qualy', 0),
    ('fuel_calculator', 'footer.lap_delta_optimal', 'practice', 0),
    ('fuel_calculator', 'footer.lap_delta_optimal', 'race', 0),
    ('fuel_calculator', 'footer.lap_delta_optimal', 'qualy', 0),
    (
        'fuel_calculator',
        'footer.lap_delta_session_best',
        'practice',
        0
    ),
    ('fuel_calculator', 'footer.lap_delta_session_best', 'race', 0),
    ('fuel_calculator', 'footer.lap_delta_session_best', 'qualy', 0),
    (
        'fuel_calculator',
        'footer.lap_delta_session_optimal',
        'practice',
        0
    ),
    (
        'fuel_calculator',
        'footer.lap_delta_session_optimal',
        'race',
        0
    ),
    (
        'fuel_calculator',
        'footer.lap_delta_session_optimal',
        'qualy',
        0
    ),
    (
        'fuel_calculator',
        'footer.lap_delta_session_last',
        'practice',
        0
    ),
    ('fuel_calculator', 'footer.lap_delta_session_last', 'race', 0),
    ('fuel_calculator', 'footer.lap_delta_session_last', 'qualy', 0),
    ('fuel_calculator', 'footer.brake_bias', 'practice', 0),
    ('fuel_calculator', 'footer.brake_bias', 'race', 0),
    ('fuel_calculator', 'footer.brake_bias', 'qualy', 0),
    ('fuel_calculator', 'footer.fuel_level', 'practice', 0),
    ('fuel_calculator', 'footer.fuel_level', 'race', 0),
    ('fuel_calculator', 'footer.fuel_level', 'qualy', 0),
    ('fuel_calculator', 'footer.water_temp', 'practice', 0),
    ('fuel_calculator', 'footer.water_temp', 'race', 0),
    ('fuel_calculator', 'footer.water_temp', 'qualy', 0),
    ('fuel_calculator', 'footer.oil_temp', 'practice', 0),
    ('fuel_calculator', 'footer.oil_temp', 'race', 0),
    ('fuel_calculator', 'footer.oil_temp', 'qualy', 0),
    ('fuel_calculator', 'footer.sof', 'practice', 0),
    ('fuel_calculator', 'footer.sof', 'race', 0),
    ('fuel_calculator', 'footer.sof', 'qualy', 0),
    ('fuel_calculator', 'footer.current_stint_in_laps', 'practice', 0),
    ('fuel_calculator', 'footer.current_stint_in_laps', 'race', 0),
    ('fuel_calculator', 'footer.current_stint_in_laps', 'qualy', 0),
    ('fuel_calculator', 'footer.current_stint_in_time', 'practice', 0),
    ('fuel_calculator', 'footer.current_stint_in_time', 'race', 0),
    ('fuel_calculator', 'footer.current_stint_in_time', 'qualy', 0),
    ('fuel_calculator', 'footer.rpm', 'practice', 0),
    ('fuel_calculator', 'footer.rpm', 'race', 0),
    ('fuel_calculator', 'footer.rpm', 'qualy', 0),
    ('fuel_calculator', 'footer.deploy_mode', 'practice', 0),
    ('fuel_calculator', 'footer.deploy_mode', 'race', 0),
    ('fuel_calculator', 'footer.deploy_mode', 'qualy', 0),
    ('fuel_calculator', 'footer.arb_front', 'practice', 0),
    ('fuel_calculator', 'footer.arb_front', 'race', 0),
    ('fuel_calculator', 'footer.arb_front', 'qualy', 0),
    ('fuel_calculator', 'footer.arb_rear', 'practice', 0),
    ('fuel_calculator', 'footer.arb_rear', 'race', 0),
    ('fuel_calculator', 'footer.arb_rear', 'qualy', 0),
    ('fuel_calculator', 'footer.abs', 'practice', 0),
    ('fuel_calculator', 'footer.abs', 'race', 0),
    ('fuel_calculator', 'footer.abs', 'qualy', 0),
    ('fuel_calculator', 'footer.tc_1', 'practice', 0),
    ('fuel_calculator', 'footer.tc_1', 'race', 0),
    ('fuel_calculator', 'footer.tc_1', 'qualy', 0),
    ('fuel_calculator', 'footer.tc_2', 'practice', 0),
    ('fuel_calculator', 'footer.tc_2', 'race', 0),
    ('fuel_calculator', 'footer.tc_2', 'qualy', 0),
    ('fuel_calculator', 'footer.weight_jacker', 'practice', 0),
    ('fuel_calculator', 'footer.weight_jacker', 'race', 0),
    ('fuel_calculator', 'footer.weight_jacker', 'qualy', 0),
    ('fuel_calculator', 'footer.rear_brake_valve', 'practice', 0),
    ('fuel_calculator', 'footer.rear_brake_valve', 'race', 0),
    ('fuel_calculator', 'footer.rear_brake_valve', 'qualy', 0),
    ('fuel_calculator', 'footer.precippitation', 'practice', 0),
    ('fuel_calculator', 'footer.precippitation', 'race', 0),
    ('fuel_calculator', 'footer.precippitation', 'qualy', 0),
    ('fuel_calculator', 'footer.track_wetness', 'practice', 0),
    ('fuel_calculator', 'footer.track_wetness', 'race', 0),
    ('fuel_calculator', 'footer.track_wetness', 'qualy', 0),
    ('fuel_calculator', 'footer.weather_declared_wet', 'practice', 0),
    ('fuel_calculator', 'footer.weather_declared_wet', 'race', 0),
    ('fuel_calculator', 'footer.weather_declared_wet', 'qualy', 0),
    ('fuel_calculator', 'footer.pit_time_loss', 'practice', 0),
    ('fuel_calculator', 'footer.pit_time_loss', 'race', 0),
    ('fuel_calculator', 'footer.pit_time_loss', 'qualy', 0),
    (
        'fuel_calculator',
        'footer.wind_direction_for_driver',
        'practice',
        0
    ),
    ('fuel_calculator', 'footer.wind_direction_for_driver', 'race', 0),
    ('fuel_calculator', 'footer.wind_direction_for_driver', 'qualy', 0),
    (
        'fuel_calculator',
        'footer.predicted_position_after_pit_stop',
        'practice',
        0
    ),
    (
        'fuel_calculator',
        'footer.predicted_position_after_pit_stop',
        'race',
        0
    ),
    (
        'fuel_calculator',
        'footer.predicted_position_after_pit_stop',
        'qualy',
        0
    ),
    ('fuel_calculator', 'footer.irating_and_gain', 'practice', 0),
    ('fuel_calculator', 'footer.irating_and_gain', 'race', 0),
    ('fuel_calculator', 'footer.irating_and_gain', 'qualy', 0),
    ('fuel_calculator', 'footer.push_to_pass', 'practice', 0),
    ('fuel_calculator', 'footer.push_to_pass', 'race', 0),
    ('fuel_calculator', 'footer.push_to_pass', 'qualy', 0) ON CONFLICT (page, setting, session) DO NOTHING;