export const DISPLAY_OPTIONS = [
  { title: "Session name" },
  { title: "Event type" },
  { title: "Track name" },
  { title: "Local time (24h)" },
  { title: "Local time (am/pm)" },
  { title: "In sim time (24)" },
  { title: "In sim time (am/pm)" },
  { title: "Air temp" },
  { title: "Track temp" },
  { title: "Humidity" },
  { title: "Fog levels" },
  { title: "Time remaining" },
  { title: "Laps remaining" },
  { title: "Incident count" },
  { title: "Current lap time" },
  { title: "Session best lap time" },
  { title: "Last lap time" },
  { title: "Last lap time calculated" },
  { title: "Lap delta, best" },
  { title: "Lap delta, optimal" },
  { title: "Lap delta, session best" },
  { title: "Lap delta, session optimal" },
  { title: "Lap delta, session last" },
  { title: "Brake bias" },
  { title: "Fuel level" },
  { title: "Water temp" },
  { title: "Oil temp" },
  { title: "SOF" },
  { title: "Current stint in laps" },
  { title: "Current stint in time" },
  { title: "RPM" },
  { title: "Display mode" },
  { title: "ABS Front" },
  { title: "ABS Rear" },
  { title: "ABS" },
  { title: "TC(1)" },
  { title: "TC(2)" },
  { title: "Weight jacker" },
  { title: "Rear brake value" },
  { title: "Precipitation" },
  { title: "Track wetness" },
  { title: "Weather declared wet" },
  { title: "Pit time lost (beta)" },
  { title: "Wind direction for driver" },
  { title: "Predicted position after pit stop" },
  { title: "iRating & gain" },
  { title: "Push to pass" },
];
