/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetIndexRouteImport } from './routes/widget/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WidgetTrackMapIndexRouteImport } from './routes/widget/track-map/index'
import { Route as WidgetStandingsIndexRouteImport } from './routes/widget/standings/index'
import { Route as WidgetInputsIndexRouteImport } from './routes/widget/inputs/index'
import { Route as DashboardTwitchChatIndexRouteImport } from './routes/dashboard/twitch-chat/index'
import { Route as DashboardTrafficIndicatorIndexRouteImport } from './routes/dashboard/traffic-indicator/index'
import { Route as DashboardTrackMapIndexRouteImport } from './routes/dashboard/track-map/index'
import { Route as DashboardStandingsIndexRouteImport } from './routes/dashboard/standings/index'
import { Route as DashboardSpotterIndexRouteImport } from './routes/dashboard/spotter/index'
import { Route as DashboardRelativeIndexRouteImport } from './routes/dashboard/relative/index'
import { Route as DashboardPitHelperIndexRouteImport } from './routes/dashboard/pit-helper/index'
import { Route as DashboardInputsIndexRouteImport } from './routes/dashboard/inputs/index'
import { Route as DashboardInputsGraphIndexRouteImport } from './routes/dashboard/inputs-graph/index'
import { Route as DashboardFuelCalculatorIndexRouteImport } from './routes/dashboard/fuel-calculator/index'
import { Route as DashboardFlatMapIndexRouteImport } from './routes/dashboard/flat-map/index'
import { Route as DashboardDeltaBarIndexRouteImport } from './routes/dashboard/delta-bar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetIndexRoute = WidgetIndexRouteImport.update({
  id: '/widget/',
  path: '/widget/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetTrackMapIndexRoute = WidgetTrackMapIndexRouteImport.update({
  id: '/widget/track-map/',
  path: '/widget/track-map/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetStandingsIndexRoute = WidgetStandingsIndexRouteImport.update({
  id: '/widget/standings/',
  path: '/widget/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetInputsIndexRoute = WidgetInputsIndexRouteImport.update({
  id: '/widget/inputs/',
  path: '/widget/inputs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTwitchChatIndexRoute =
  DashboardTwitchChatIndexRouteImport.update({
    id: '/dashboard/twitch-chat/',
    path: '/dashboard/twitch-chat/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTrafficIndicatorIndexRoute =
  DashboardTrafficIndicatorIndexRouteImport.update({
    id: '/dashboard/traffic-indicator/',
    path: '/dashboard/traffic-indicator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTrackMapIndexRoute = DashboardTrackMapIndexRouteImport.update({
  id: '/dashboard/track-map/',
  path: '/dashboard/track-map/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStandingsIndexRoute = DashboardStandingsIndexRouteImport.update({
  id: '/dashboard/standings/',
  path: '/dashboard/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpotterIndexRoute = DashboardSpotterIndexRouteImport.update({
  id: '/dashboard/spotter/',
  path: '/dashboard/spotter/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRelativeIndexRoute = DashboardRelativeIndexRouteImport.update({
  id: '/dashboard/relative/',
  path: '/dashboard/relative/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPitHelperIndexRoute = DashboardPitHelperIndexRouteImport.update({
  id: '/dashboard/pit-helper/',
  path: '/dashboard/pit-helper/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInputsIndexRoute = DashboardInputsIndexRouteImport.update({
  id: '/dashboard/inputs/',
  path: '/dashboard/inputs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInputsGraphIndexRoute =
  DashboardInputsGraphIndexRouteImport.update({
    id: '/dashboard/inputs-graph/',
    path: '/dashboard/inputs-graph/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFuelCalculatorIndexRoute =
  DashboardFuelCalculatorIndexRouteImport.update({
    id: '/dashboard/fuel-calculator/',
    path: '/dashboard/fuel-calculator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFlatMapIndexRoute = DashboardFlatMapIndexRouteImport.update({
  id: '/dashboard/flat-map/',
  path: '/dashboard/flat-map/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeltaBarIndexRoute = DashboardDeltaBarIndexRouteImport.update({
  id: '/dashboard/delta-bar/',
  path: '/dashboard/delta-bar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/widget': typeof WidgetIndexRoute
  '/dashboard/delta-bar': typeof DashboardDeltaBarIndexRoute
  '/dashboard/flat-map': typeof DashboardFlatMapIndexRoute
  '/dashboard/fuel-calculator': typeof DashboardFuelCalculatorIndexRoute
  '/dashboard/inputs-graph': typeof DashboardInputsGraphIndexRoute
  '/dashboard/inputs': typeof DashboardInputsIndexRoute
  '/dashboard/pit-helper': typeof DashboardPitHelperIndexRoute
  '/dashboard/relative': typeof DashboardRelativeIndexRoute
  '/dashboard/spotter': typeof DashboardSpotterIndexRoute
  '/dashboard/standings': typeof DashboardStandingsIndexRoute
  '/dashboard/track-map': typeof DashboardTrackMapIndexRoute
  '/dashboard/traffic-indicator': typeof DashboardTrafficIndicatorIndexRoute
  '/dashboard/twitch-chat': typeof DashboardTwitchChatIndexRoute
  '/widget/inputs': typeof WidgetInputsIndexRoute
  '/widget/standings': typeof WidgetStandingsIndexRoute
  '/widget/track-map': typeof WidgetTrackMapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/widget': typeof WidgetIndexRoute
  '/dashboard/delta-bar': typeof DashboardDeltaBarIndexRoute
  '/dashboard/flat-map': typeof DashboardFlatMapIndexRoute
  '/dashboard/fuel-calculator': typeof DashboardFuelCalculatorIndexRoute
  '/dashboard/inputs-graph': typeof DashboardInputsGraphIndexRoute
  '/dashboard/inputs': typeof DashboardInputsIndexRoute
  '/dashboard/pit-helper': typeof DashboardPitHelperIndexRoute
  '/dashboard/relative': typeof DashboardRelativeIndexRoute
  '/dashboard/spotter': typeof DashboardSpotterIndexRoute
  '/dashboard/standings': typeof DashboardStandingsIndexRoute
  '/dashboard/track-map': typeof DashboardTrackMapIndexRoute
  '/dashboard/traffic-indicator': typeof DashboardTrafficIndicatorIndexRoute
  '/dashboard/twitch-chat': typeof DashboardTwitchChatIndexRoute
  '/widget/inputs': typeof WidgetInputsIndexRoute
  '/widget/standings': typeof WidgetStandingsIndexRoute
  '/widget/track-map': typeof WidgetTrackMapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/widget/': typeof WidgetIndexRoute
  '/dashboard/delta-bar/': typeof DashboardDeltaBarIndexRoute
  '/dashboard/flat-map/': typeof DashboardFlatMapIndexRoute
  '/dashboard/fuel-calculator/': typeof DashboardFuelCalculatorIndexRoute
  '/dashboard/inputs-graph/': typeof DashboardInputsGraphIndexRoute
  '/dashboard/inputs/': typeof DashboardInputsIndexRoute
  '/dashboard/pit-helper/': typeof DashboardPitHelperIndexRoute
  '/dashboard/relative/': typeof DashboardRelativeIndexRoute
  '/dashboard/spotter/': typeof DashboardSpotterIndexRoute
  '/dashboard/standings/': typeof DashboardStandingsIndexRoute
  '/dashboard/track-map/': typeof DashboardTrackMapIndexRoute
  '/dashboard/traffic-indicator/': typeof DashboardTrafficIndicatorIndexRoute
  '/dashboard/twitch-chat/': typeof DashboardTwitchChatIndexRoute
  '/widget/inputs/': typeof WidgetInputsIndexRoute
  '/widget/standings/': typeof WidgetStandingsIndexRoute
  '/widget/track-map/': typeof WidgetTrackMapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/widget'
    | '/dashboard/delta-bar'
    | '/dashboard/flat-map'
    | '/dashboard/fuel-calculator'
    | '/dashboard/inputs-graph'
    | '/dashboard/inputs'
    | '/dashboard/pit-helper'
    | '/dashboard/relative'
    | '/dashboard/spotter'
    | '/dashboard/standings'
    | '/dashboard/track-map'
    | '/dashboard/traffic-indicator'
    | '/dashboard/twitch-chat'
    | '/widget/inputs'
    | '/widget/standings'
    | '/widget/track-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/widget'
    | '/dashboard/delta-bar'
    | '/dashboard/flat-map'
    | '/dashboard/fuel-calculator'
    | '/dashboard/inputs-graph'
    | '/dashboard/inputs'
    | '/dashboard/pit-helper'
    | '/dashboard/relative'
    | '/dashboard/spotter'
    | '/dashboard/standings'
    | '/dashboard/track-map'
    | '/dashboard/traffic-indicator'
    | '/dashboard/twitch-chat'
    | '/widget/inputs'
    | '/widget/standings'
    | '/widget/track-map'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/widget/'
    | '/dashboard/delta-bar/'
    | '/dashboard/flat-map/'
    | '/dashboard/fuel-calculator/'
    | '/dashboard/inputs-graph/'
    | '/dashboard/inputs/'
    | '/dashboard/pit-helper/'
    | '/dashboard/relative/'
    | '/dashboard/spotter/'
    | '/dashboard/standings/'
    | '/dashboard/track-map/'
    | '/dashboard/traffic-indicator/'
    | '/dashboard/twitch-chat/'
    | '/widget/inputs/'
    | '/widget/standings/'
    | '/widget/track-map/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  WidgetIndexRoute: typeof WidgetIndexRoute
  DashboardDeltaBarIndexRoute: typeof DashboardDeltaBarIndexRoute
  DashboardFlatMapIndexRoute: typeof DashboardFlatMapIndexRoute
  DashboardFuelCalculatorIndexRoute: typeof DashboardFuelCalculatorIndexRoute
  DashboardInputsGraphIndexRoute: typeof DashboardInputsGraphIndexRoute
  DashboardInputsIndexRoute: typeof DashboardInputsIndexRoute
  DashboardPitHelperIndexRoute: typeof DashboardPitHelperIndexRoute
  DashboardRelativeIndexRoute: typeof DashboardRelativeIndexRoute
  DashboardSpotterIndexRoute: typeof DashboardSpotterIndexRoute
  DashboardStandingsIndexRoute: typeof DashboardStandingsIndexRoute
  DashboardTrackMapIndexRoute: typeof DashboardTrackMapIndexRoute
  DashboardTrafficIndicatorIndexRoute: typeof DashboardTrafficIndicatorIndexRoute
  DashboardTwitchChatIndexRoute: typeof DashboardTwitchChatIndexRoute
  WidgetInputsIndexRoute: typeof WidgetInputsIndexRoute
  WidgetStandingsIndexRoute: typeof WidgetStandingsIndexRoute
  WidgetTrackMapIndexRoute: typeof WidgetTrackMapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/': {
      id: '/widget/'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/track-map/': {
      id: '/widget/track-map/'
      path: '/widget/track-map'
      fullPath: '/widget/track-map'
      preLoaderRoute: typeof WidgetTrackMapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/standings/': {
      id: '/widget/standings/'
      path: '/widget/standings'
      fullPath: '/widget/standings'
      preLoaderRoute: typeof WidgetStandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/inputs/': {
      id: '/widget/inputs/'
      path: '/widget/inputs'
      fullPath: '/widget/inputs'
      preLoaderRoute: typeof WidgetInputsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/twitch-chat/': {
      id: '/dashboard/twitch-chat/'
      path: '/dashboard/twitch-chat'
      fullPath: '/dashboard/twitch-chat'
      preLoaderRoute: typeof DashboardTwitchChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/traffic-indicator/': {
      id: '/dashboard/traffic-indicator/'
      path: '/dashboard/traffic-indicator'
      fullPath: '/dashboard/traffic-indicator'
      preLoaderRoute: typeof DashboardTrafficIndicatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/track-map/': {
      id: '/dashboard/track-map/'
      path: '/dashboard/track-map'
      fullPath: '/dashboard/track-map'
      preLoaderRoute: typeof DashboardTrackMapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/standings/': {
      id: '/dashboard/standings/'
      path: '/dashboard/standings'
      fullPath: '/dashboard/standings'
      preLoaderRoute: typeof DashboardStandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/spotter/': {
      id: '/dashboard/spotter/'
      path: '/dashboard/spotter'
      fullPath: '/dashboard/spotter'
      preLoaderRoute: typeof DashboardSpotterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/relative/': {
      id: '/dashboard/relative/'
      path: '/dashboard/relative'
      fullPath: '/dashboard/relative'
      preLoaderRoute: typeof DashboardRelativeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pit-helper/': {
      id: '/dashboard/pit-helper/'
      path: '/dashboard/pit-helper'
      fullPath: '/dashboard/pit-helper'
      preLoaderRoute: typeof DashboardPitHelperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inputs/': {
      id: '/dashboard/inputs/'
      path: '/dashboard/inputs'
      fullPath: '/dashboard/inputs'
      preLoaderRoute: typeof DashboardInputsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inputs-graph/': {
      id: '/dashboard/inputs-graph/'
      path: '/dashboard/inputs-graph'
      fullPath: '/dashboard/inputs-graph'
      preLoaderRoute: typeof DashboardInputsGraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fuel-calculator/': {
      id: '/dashboard/fuel-calculator/'
      path: '/dashboard/fuel-calculator'
      fullPath: '/dashboard/fuel-calculator'
      preLoaderRoute: typeof DashboardFuelCalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flat-map/': {
      id: '/dashboard/flat-map/'
      path: '/dashboard/flat-map'
      fullPath: '/dashboard/flat-map'
      preLoaderRoute: typeof DashboardFlatMapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/delta-bar/': {
      id: '/dashboard/delta-bar/'
      path: '/dashboard/delta-bar'
      fullPath: '/dashboard/delta-bar'
      preLoaderRoute: typeof DashboardDeltaBarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  WidgetIndexRoute: WidgetIndexRoute,
  DashboardDeltaBarIndexRoute: DashboardDeltaBarIndexRoute,
  DashboardFlatMapIndexRoute: DashboardFlatMapIndexRoute,
  DashboardFuelCalculatorIndexRoute: DashboardFuelCalculatorIndexRoute,
  DashboardInputsGraphIndexRoute: DashboardInputsGraphIndexRoute,
  DashboardInputsIndexRoute: DashboardInputsIndexRoute,
  DashboardPitHelperIndexRoute: DashboardPitHelperIndexRoute,
  DashboardRelativeIndexRoute: DashboardRelativeIndexRoute,
  DashboardSpotterIndexRoute: DashboardSpotterIndexRoute,
  DashboardStandingsIndexRoute: DashboardStandingsIndexRoute,
  DashboardTrackMapIndexRoute: DashboardTrackMapIndexRoute,
  DashboardTrafficIndicatorIndexRoute: DashboardTrafficIndicatorIndexRoute,
  DashboardTwitchChatIndexRoute: DashboardTwitchChatIndexRoute,
  WidgetInputsIndexRoute: WidgetInputsIndexRoute,
  WidgetStandingsIndexRoute: WidgetStandingsIndexRoute,
  WidgetTrackMapIndexRoute: WidgetTrackMapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
